			{"allies"
				{title "ALLIES"}
				{armies "usa"}
				{armies "eng"}
				{armies "rus"}
				{armies "fra"}
				{armies "chn"}
				{icon "/interface/pages/multi/flag_allies"}
			}
                        {"axis" 
				{title "AXIS"}
				{armies "ger"}
				{armies "jap"}
                                {armies "ita"}
                                {armies "hun"}
                                {armies "fin"}
				{icon "/interface/pages/multi/flag_axis"}
			}
			