(define "firing"
	{fin_noscope 0.0}
	{welrod 0.6}
	{nagan_pb 0.6}
	{delisle 1.2}
	{hdm 0.6}
	{sten_v_silencer 0.6}
	{knife_ger 0}
	{knife_rus 0}
	{knife_union 0}
	{knife_japan 0}
	{axe 0}	
	{crow_bar 0}
	{smoke 0.1}
	{smoke_paradrop_ammo 0.1}
	{smoke_paradrop_ammo_heavy 0.1}
	{f1 0.1}
	{m24 0.1}
	{m39 0.1}
	{m61 0.1}
	{mk1 0.1}
	{satchel 0.1}
	{type97 0.1}
	{type99 0.1}
	{m24x5 0.1}
	{molotov_coctail 0.1}
	{n73at 0.1}
	{pwm1 0.1}
	{rg42x3 0.1}
	{rpg40 0.1}
	{rpg43 0.1}
	{type3at 0.1}
	{type3at_a 0.1}
	{type99at 0.1}

;ADD RIFLES
	{zh_29  1.5}
	{typezhongzheng 1.5}
	{pystykorva 1.5}
	{mauzer1924 1.5}
	{mas36_grenade 1.5}
	{mas36  1.5}
	{mannlicher_m1895c  1.5}
	{mannlicher_m1895 1.5}
	{lebel_m1886  1.5}
	{gewehrgranatgerat  1.5}
	{feg_43m 1.5}
	{carcano_m91_38   1.5}
	{carcano_m91  1.5}
	{Carcano_m1891bayonet 1.5}
	{berthier_m1916   1.5}
	{avs36  1.5}
;DEFAULT RIFLES
	{type99rifle_at 1.5}
	{type99rifle  1.5}
	{type2rifle  1.5}
	{svt40  1.5}
	{sks 1.5}
	{mosin   1.5}
	{mauzer   1.5}	
	{m2_carbine   1.5}	
	{m1_carbine  1.5}	
	{m1903   1.5}
	{m12_shotgun   1.5}	
	{johnson 1.5}
	{garand  1.5}
	{g43_scope 1.5}
	{g43 1.5}
	{em3_mark1  1.5}
	{em3 1.5}
 ;PTR
	{type_97_antitank 2}
	{pzb39 2}
	{ptrs 2}
	{ptrd 2}
	{boyes 2}
	{wz35 2}
	{solothurn 2}
 ;SNIPER
	{zb24_s  2}
	{mauser_zhongzheng_scope 2}
	{lebel_m1886_scoped   2}
	{carcano_m91_scoped  2}
	{type99rifle_s  2}
	{mosin_s 2}
	{m1903a4  2}
	{g41  2}
	{em2 2}
;DEFAULT SMG
	{type2smg 1.5}
	{type100smg   1.5}	
	{thompson_m1928   1.5}
	{thompson_30  1.5}
	{thompson 1.5}
	{sten_v 1.5}
	{sten  1.5} 
	{sg44 1.5}
	{ppsh41   1.5}
	{ppsh   1.5}
	{pps43  1.5}
	{owen_gun 1.5}
	{mp40  1.5}
	{mp3008 1.5}
	{mp28_50  1.5}
	{mp28   1.5}
	{m50reising   1.5}
	{m3a  1.5}
;ADD SMG
	{suomi_m31 1.5}
	{ppd40  1.5}
	{ppd 1.5}
	{mp18 1.5}
	{mas38  1.5}
	{mab_42 1.5}
	{mab_38a 1.5}
	{danuvia_43m 1.5}
	{danuvia_39m  1.5}
;add pistol
	{modele_1935 1.5}
	{mauser_pistol   1.5}
	{frommer_37m  1.5}
	{Beretta_m1934stunn   1.5}
	{beretta_m1934 1.5}
;DEFAULT PISTOL
	{webley 1.5}
	{valter   1.5}
	{tt  1.5}
	{nambu   1.5}
	{nagan 1.5}
	{webley  1.5}
	{valter  1.5}
	{luger  1.5}
	{flaergun  1.5}
	{colt 1.5}
;DEFAULT MG
 
	{vickers_mgun 2}
	{vickers_k  2}
	{type99lmg 2}
	{type1hmg  2}
	{mg42_120  2}
	{mg42 2}
	{mg37 2}
	{mg34_x2  2}
	{mg34_tower  2}
	{mg34 2}
	{maxim_inv 2}
	{maxim   2}
	{johnson_m1941 2}
	{fg42  	2}
	{dt   	2}
	{dshk 2}
	{ds 2}
	{dp 2}
	{browning_x4  2}
	{browning_x2  2}
	{browning_m19a6 2}
	{browning_m19	2}
	{bren  2}
	{besa 2}
	{bar 2}

;ADD MG
	{zb26 2}
	{vickers_k_x2 2}
	{solothurn_31m 2}
	{Reibel 2}
	{mg13   2}
	{maxim_quad 2}
	{maxim_norm  2}
	{maxim_mg08   	2}
	{maxim_indirect   2}
	{maxim_32  2}
	{lsm26   2}
	{kgm40   2}
	{johnson_m1941  2}
	{hotchkiss_132  2}
	{hotchkiss132   2}
	{gebauer   2}
	{fm_24_29_t	2}
	{fm_24_29   	2}
	{fiat_65_x2   	2}
	{fiat_65  	2}
	{fiatm1914  	2}
	{dt_2x   		2}
	{ckm_wz30   	2}
	{chauchat_mle_15	2}
	{browning_m17	2}
	{breda_safat88	2}
	{breda_38_x2 	2}
	{breda_38	2}
	{breda_30	2}
	{bredam38x2	2}
	{bredam38	2}
	{schwarzlose	2}

)
(define "vision"
	{cover 0.80
		{stand 0.80
			{stealth 0.40}		; 50%
		}
		{squat 0.60
			{stealth 0.30}		; 50%
		}
		{crawl 0.40
			{stealth 0.20}		; 50%
		}
    }
    {squat 0.80
        {stealth 0.40}			; 50%
	}
    {crawl 0.60
        {stealth 0.30}			; 50%
        {still 0.40
            {stealth 0.20}		; 50%
        }
    }
    {still 0.9}
    {visible 1.0}
)

(define "cannon"
        {cannon_01 1
            {firing 1.1}
            {visible 1}
            {still 1}
        }
        {cannon_02 1.1
            {firing 1.2}
            {visible 1.1}
            {still 1.1}
        }
        {cannon_03 1.2
            {firing 1.3}
            {visible 1.2}
            {still 1.2}
        }
        {cannon_04 1.3
            {firing 1.4}
            {visible 1.3}
            {still 1.3}
        }
        {cannon_05 1.4
            {firing 1.5}
            {visible 1.4}
            {still 1.4}
        }
)
(define "tank"
        {vehicle_01 1.1
            {firing 2.0}
            {visible 1.6}
            {still 1.6}
        }
        {vehicle_02 1.8
            {firing 2.25}
            {visible 1.7}
            {still 1.7}
        }
        {vehicle_03 2.0
            {firing 2.5}
            {visible 1.8}
            {still 1.8}
        }
        {vehicle_04 2.2
            {firing 2.75}
            {visible 1.9}
            {still 1.9}
        }
        {vehicle_05 2.4
            {firing 3}
            {visible 2}
            {still 2}
        }
)