		{"mp"		
			{"chn"
				{"ap_miner" "combat Engineer (AP mines)"}
				{"at_miner" "combat Engineer (AT mines)"}
				{"at_rifle" "AT-Rifle infantry"}
				{"at_rifle2" "AT-Rifle support infantry"}
				{"elite" "foreign-trained solider"}
				{"elite2" "foreign-trained solider"}
				{"elite3" "foreign-trained solider"}
				{"engineer" "engineer"}
				{"flamer" "flamethrower infantry"}
				{"flamer2" "flamethrower support infantry"}
				{"home_guard" "peasent"}
				{"home_guard2" "peasent"}
                {"home_guard3" "Rice Farmer"}
				{"home_guard4" "Rice Farmer"}
				{"mgun" "machine Gunner"}
				{"mgun2" "machine gunner"}
				{"mgun3" "machine gunner"}
				{"medic" "medic"}
				{"oficer" "Officer"}
                {"oficer3" "communist warlord"}
				{"rifle" "rifleman"}
				{"rifle2" "rifleman"}
				{"rifle3" "rifleman"}
				{"saper" "sapper"}
				{"smg" "SMG infantry"}
				{"smg2" "assault SMG infantry"}
				{"sniper" "Sniper"}
				{"sturmovik" "stormtrooper"}
				{"sturmovik2" "stormtrooper"}
				{"sturmovik3" "stormtrooper"}
				{"sturmovik4" "stormtrooper"}
				{"tankman" "tank crew"}
				{"tankman2" "tank commander"}
				{"radioman" "radio operator"}
				{"squadleader" "squad leader"}
				{"squadleader2" "assault squad leader"}
				{"vehicle_supporter" "soldier"}
			}
		}
	