                {"gnome" "Gnome & Rhone AX2 800"} 
                {"m3_fra" "M3A1"}
                {"renault_inf" "Renault"}
                {"renault_art" "Renault"}
                {"renault_eng" "Renault"}
                {"laffly_v15t" "Laffly v15t"}
                {"laffly_s15_toe" "Laffly S15 toe"}
                {"hotchkiss_stan" "Heavy MG"}
                {"13mm_hotchkiss" "Hotchkiss M1929"}
                {"mle_27" "81mm mle.27/31"}
                {"25mm_hotchkiss_mle34" "25mm SA-L.1934"}
                {"47mm_puteaux_mle37" "47mm SA.1937"}
                {"75mm_vickers" "75mm Vickers AA"}
                {"37mm_shneider" "37mm DCA Shneider"}
		{"how_a(fra)" "BL 6\\26 cwt"}
		{"how_b(fra)" "QF 25-pdr"}
                {"how_a(fra2)" "BL 6\\26 cwt"}
                {"how_b(fra2)" "QF 25-pdr"}
		{"ft17" "Renault FT-17"}
		{"morriscs9_fra" "Morris CS9"}
		{"amr35-13mm" "AMR35 ZT 1-13mm"}
		{"panhard" "Panhard 178"}
		{"r35" "Renault R-35"}
		{"r35_anz" "Renault R-35"}
		{"h39" "Hotchkiss H-39"}
		{"d2" "Char D2"}
		{"s35" "Somua S-35"}
		{"b1bis" "Renault B1 bis"}
		{"b1bis_3" "Renault B1 bis-ter"}
		{"lorraine_47" "Lorraine 37L-47mm SA.1937"}
		{"b1bis_at" "Renault B1 bis 75mm Antichar"}
                {"b1bis_at" "Renault B1 bis 75mm Antichar"}
                {"mortarlightuk" "Mortier de 50mm"}
                {"amx-13-90" "AMX-13/75"}
                {"amx50-100" "AMX-50/100"}
                {"citroen45_mort" "Citroen Mortar Truck"}
