		{"r12_fin" "BMW R12"}
		{"np_volvo_inf" "Volvo LV120"}
		{"np_volvo_art"  "Volvo LV120"}
		{"np_volvo_eng"   "Volvo LV120"}
		{"maxim_stan"  "Heavy MG"}
		{"37mm_bofors_fin"  "37mm AT Bofors"}
		{"flak38_wheeled_fin" "Flak 38"}
		{"76mm_m1902_30_l30" "76mm M1902/30"}
		{"76mm_m1909_fin" "76mm M1909"}
		{"sgrw42_fin" "KrH 120 mortar"}
		{"how_a(fin)" "sFH 18"}
		{"how_b(fin)" "le. FH 18 M"}
				{"how_a(fin2)" "sFH 18"}
		{"how_b(fin2)" "le. FH 18 M"}
		{"122mm_howitzer_m1910_fin" "122mm Howitzer M1910"}
		{"152mm_m1909_30_fin" "152mm M1909/30"}
		{"np_ba20_fin"  "BA-20"}
		{"ba10_fin" "BA-10"}
		{"ft17_fin" "FT-17"} 
		{"t-26_fin_1931" "T-26 mod.1931"} 
		{"vickers_fin"  "Vickers"} 	
		{"t-26_fin_1933"  "T-26 mod.1933"} 
		{"ot-130"  "OT-130"} 
		{"bt5_fin" "BT-5"} 
		{"t20_fin" "T-20"} 
		{"20_mm_lahti_l_39" "20mm Lahti L-39"}
		{"maxim_m_32_33" "Maxim M/32-33"}
		{"t28_fin" "T-28"} 
		{"t28_l10_fin" "T-28M"} 
		{"bt5" "BT-5"} 
		{"vickers37_fin" "Vickers 37mm"} 
		{"bofors_fin" "40mm Bofors"}
		{"pak40_fin" "PaK 40"}
		{"kv1_41_fin" "KV-1 mod. 40"}
		{"t50_fin" "T-50"}
		{"pz4jfin" "PzKpfw IV Ausf.J"}
		{"stug3gfin" "StuG III Ausf.G"}
		{"t34_3_fin" "T-34/85"} 
		{"bt42" "BT-42"} 
		{"landsverk_anti_2" " Landsverk Anti-II"}
		{"np_ml20_fin_veteran" "Veteran 152mm M1937"}
		{"su152" "SU-152"} 
		{"maxim_ind" "Maxim"} 
		{"itk31" "76 ItK/31 BK"} 
		{"t34_41_fin" "T-34 1941 mod"}
		{"t34_42_fin" "T-34 1942 mod"}