		{"mauser_pistol" "Mauser pistol"}
		{"taisho11" "type taisho11"}
		{"mp18" "MP-18"}
		{"zb26" "ZB vz.26"}
		{"typezhongzheng" "typezhongzheng rifle"}
		{"maxim_quad" "Maxim quad"}
		{"arisaka" "Arisaka"}
		{"browning_m17" "Browning M1917 "}
		{"backsack_1" "Backsack"}
		{"cha_broadsword" "Broadsword"}
		{"cha_broadsword2" "Broadsword"}
		{"jap-falchion" "Falchion"}
		{"m1897" "M1897"}
		{"mauzer1924" "Mauzer 1924"}
		{"m1928a1_drum" "M1928a1"}
		{"type38" "Type 38"}
		{"type38ex" "Type 38(ex)"}
		{"type89zhidan" "Type 89 zhidan"}
		{"type92" "Type 92"}
		{"type92_1" "Type 92"}


