		{"mp"
			{"rus"
				{"ap_miner" "<c(c3baae)>combat engineer (infantry)"}
				{"at_miner" "<c(c3baae)>combat engineer (vehicle)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>marine"}
				{"elite2" "<c(c3baae)>marine"}
				{"elite3" "<c(c3baae)>marine"}
				{"elite4" "<c(c3baae)>guards rifle"}
				{"elite5" "<c(c3baae)>guards rifle"}
				{"elite6" "<c(c3baae)>guards rifle"}
				{"elite_at" "<c(c3baae)>marine"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"flamer3" "<c(c3baae)>shock infantry"}
				{"home_guard" "<c(c3baae)>partisan"}
				{"home_guard2" "<c(c3baae)>partisan"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"rifle3" "<c(c3baae)>rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"scout" "<c(c3baae)>spetsnaz"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"smg3" "<c(c3baae)>shock infantry"}
				{"smg4" "<c(c3baae)>shock infantry"}
				{"smg5" "<c(c3baae)>demolition specialist"}
                {"sniper" "<c(c3baae)>sniper"}
				{"sniper2" "<c(c3baae)>guards sniper"}
				{"sturmovik" "<c(c3baae)>red guard"}
				{"sturmovik2" "<c(c3baae)>red guard"}
				{"sturmovik3" "<c(c3baae)>red guard"}
				{"sturmovik4" "<c(c3baae)>red guard"}
				{"sturmovik4b" "<c(c3baae)>red guard"}
				{"sturmovik5" "<c(c3baae)>red guard"}
				{"sturmovik5b" "<c(c3baae)>red guard"}
				{"sturmovik6" "<c(c3baae)>red guard"}
				{"sturmovik6b" "<c(c3baae)>red guard"}
                {"sturmovik7" "<c(c3baae)>red guard"}
                {"sturmovik7b" "<c(c3baae)>red guard"}
				{"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
			{"usa"
				{"ap_miner" "<c(c3baae)>combat engineer (infantry)"}
				{"at_miner" "<c(c3baae)>combat engineer (vehicle)"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>airborne"}
				{"elite2" "<c(c3baae)>airborne"}
				{"elite3" "<c(c3baae)>airborne"}
				{"elite4" "<c(c3baae)>U.S. Marine"}
				{"elite5" "<c(c3baae)>U.S. Marine"}
				{"elite6" "<c(c3baae)>U.S. Marine"}
				{"elite7" "<c(c3baae)>marauder"}
				{"elite8" "<c(c3baae)>marauder"}
				{"elite9" "<c(c3baae)>marauder"}
				{"elite10" "<c(c3baae)>U.S. Marine"}
				{"elite11" "<c(c3baae)>U.S. Marine"}
                {"elite_at" "<c(c3baae)>airborne"}
				{"elite_para" "<c(c3baae)>101st Airborne"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>conscript"}
				{"home_guard2" "<c(c3baae)>conscript"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"mgun2" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"saper2" "<c(c3baae)>combat engineer"}
				{"scout" "<c(c3baae)>commando"}
				{"scout2" "<c(c3baae)>commando"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"smg3" "<c(c3baae)>demolition specialist"}
                {"sniper" "<c(c3baae)>sniper"}
				{"shotgun" "<c(c3baae)>shotgun trooper"}
				{"sturmovik" "<c(c3baae)>ranger"}
				{"sturmovik2" "<c(c3baae)>ranger"}
				{"sturmovik3" "<c(c3baae)>ranger"}
				{"sturmovik4" "<c(c3baae)>ranger"}
				{"sturmovik4b" "<c(c3baae)>ranger"}
				{"sturmovik5" "<c(c3baae)>ranger"}
				{"sturmovik5b" "<c(c3baae)>ranger"}
				{"sturmovik6" "<c(c3baae)>ranger"}
				{"sturmovik6b" "<c(c3baae)>ranger"}
				{"sturmovik7" "<c(c3baae)>ranger"}
                {"sturmovik7b" "<c(c3baae)>ranger"}
                {"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"tankman3" "<c(c3baae)>Shia LaBeouf"}
				{"tankman4" "<c(c3baae)>Brad Pitt"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
			{"ger"
				{"ap_miner" "<c(c3baae)>combat engineer (infantry)"}
				{"at_miner" "<c(c3baae)>combat engineer (vehicle)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle rifleman"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"bazooker3" "<c(c3baae)>AT infantry"}
				{"elite" "<c(c3baae)>paratrooper"}
				{"elite2" "<c(c3baae)>paratrooper"}
				{"elite3" "<c(c3baae)>paratrooper"}
				{"elite4" "<c(c3baae)>brandenburger"}
				{"elite5" "<c(c3baae)>brandenburger"}
				{"elite6" "<c(c3baae)>brandenburger"}
				{"elite_at" "<c(c3baae)>paratrooper"}
                {"elite7" "<c(c3baae)>volksgrenadier"}
                {"elite8" "<c(c3baae)>volksgrenadier"}
                {"elite9" "<c(c3baae)>volksgrenadier"}
                {"sturmovik8" "<c(c3baae)>das reich stormtrooper"}
                {"sturmovik9" "<c(c3baae)>das reich stormtrooper"}
                {"sturmovik10" "<c(c3baae)>das reich stormtrooper"}
                {"sturmovik11" "<c(c3baae)>das reich stormtrooper"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>volkssturm"}
				{"home_guard2" "<c(c3baae)>volkssturm"}
                {"home_guard3" "<c(c3baae)>german youth"}
				{"home_guard4" "<c(c3baae)>german youth"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
                {"mgun2" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"oficer2" "<c(c3baae)>waffen ss officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"smg3" "<c(c3baae)>demolition specialist"}
                {"sniper" "<c(c3baae)>sniper"}
				{"sniper2" "<c(c3baae)>veteran sniper"}
				{"sturmovik" "<c(c3baae)>panzergrenadier"}
				{"sturmovik2" "<c(c3baae)>panzergrenadier"}
				{"sturmovik3" "<c(c3baae)>panzergrenadier"}
				{"sturmovik4" "<c(c3baae)>panzergrenadier"}
				{"sturmovik4b" "<c(c3baae)>panzergrenadier"}
				{"sturmovik5" "<c(c3baae)>panzergrenadier"}
				{"sturmovik5b" "<c(c3baae)>panzergrenadier"}
				{"sturmovik6" "<c(c3baae)>panzergrenadier"}
				{"sturmovik6b" "<c(c3baae)>panzergrenadier"}
				{"sturmovik7" "<c(c3baae)>panzergrenadier"}
                {"sturmovik7b" "<c(c3baae)>panzergrenadier"}
                {"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
			{"eng"
				{"ap_miner" "<c(c3baae)>combat engineer (infantry)"}
				{"at_miner" "<c(c3baae)>combat engineer (vehicle)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>commando"}
				{"elite2" "<c(c3baae)>commando"}
				{"elite3" "<c(c3baae)>commando"}
				{"elite4" "<c(c3baae)>sacred band infantry"}
				{"elite5" "<c(c3baae)>sacred band infantry"}
				{"elite6" "<c(c3baae)>sacred band infantry"}
				{"elite_at" "<c(c3baae)>commando"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>militiaman"}
				{"home_guard2" "<c(c3baae)>militiaman"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"mgun2" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"rifle3" "<c(c3baae)>rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"saper2" "<c(c3baae)>royal engineer"}
				{"saper3" "<c(c3baae)>royal engineer"}
				{"scout" "<c(c3baae)>saboteur"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"smg3" "<c(c3baae)>SMG infantry"}
				{"smg4" "<c(c3baae)>demolition specialist"}
                {"sniper" "<c(c3baae)>sniper"}
				{"sturmovik" "<c(c3baae)>SAS soldier"}
				{"sturmovik2" "<c(c3baae)>SAS soldier"}
				{"sturmovik3" "<c(c3baae)>SAS soldier"}
				{"sturmovik4" "<c(c3baae)>SAS soldier"}
				{"sturmovik4b" "<c(c3baae)>SAS soldier"}
				{"sturmovik4c" "<c(c3baae)>SAS soldier"}
				{"sturmovik5" "<c(c3baae)>SAS soldier"}
				{"sturmovik5b" "<c(c3baae)>SAS soldier"}
				{"sturmovik6" "<c(c3baae)>SAS soldier"}
				{"sturmovik6b" "<c(c3baae)>SAS soldier"}
				{"sturmovik7" "<c(c3baae)>SAS solider"}
                {"sturmovik7b" "<c(c3baae)>SAS solider"}
                {"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
			{"jap"
				{"at_miner" "<c(c3baae)>combat engineer (infantry)"}
				{"ap_miner" "<c(c3baae)>combat engineer (vehicle)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"bazooker3" "<c(c3baae)>AT infantry"}
				{"elite" "<c(c3baae)>paratrooper"}
				{"elite2" "<c(c3baae)>paratrooper"}
				{"elite3" "<c(c3baae)>paratrooper"}
				{"elite4" "<c(c3baae)>paratrooper"}
				{"elite5" "<c(c3baae)>takasago volunteer"}
				{"elite6" "<c(c3baae)>takasago volunteer"}
				{"elite7" "<c(c3baae)>takasago volunteer"}
                {"elite_at" "<c(c3baae)>paratrooper"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>recruit"}
				{"home_guard2" "<c(c3baae)>recruit"}
				{"kamikaze" "<c(c3baae)>kamikaze"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"rifle3" "<c(c3baae)>banzai rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"smg3" "<c(c3baae)>demolition specialist"}
				{"smg4" "<c(c3baae)>banzai SMG infantry"}
                {"sniper" "<c(c3baae)>sniper"}
				{"sturmovik" "<c(c3baae)>SNLF soldier"}
				{"sturmovik2" "<c(c3baae)>SNLF soldier"}
				{"sturmovik3" "<c(c3baae)>SNLF soldier"}
				{"sturmovik4" "<c(c3baae)>SNLF soldier"}
				{"sturmovik4b" "<c(c3baae)>SNLF soldier"}
				{"sturmovik5" "<c(c3baae)>SNLF soldier"}
				{"sturmovik5b" "<c(c3baae)>SNLF soldier"}
				{"sturmovik6" "<c(c3baae)>SNLF soldier"}
				{"sturmovik6b" "<c(c3baae)>SNLF soldier"}
				{"sturmovik7" "<c(c3baae)>SNFL solider"}
                {"sturmovik7b" "<c(c3baae)>SNFL solider"}
                {"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
		}
		{"civilian"
			{"civilian1" "Civilian"}
			{"civilian2" "Civilian"}
			{"civilian3" "Civilian"}
			{"civilian4" "Civilian"}
			{"civilian5" "Civilian"}
		}
