     	{"m1139_anz" "Fiat M11/39"}
     	{"m1340_anz" "Fiat M13/40"}
     	{"m2a4" "M2A4 Stuart"}
     	{"np_lrdg_20mm" "Chevy LDGR DAK 20mm Breda"}
     	{"m3grant_anz" "M3 Grant"}
     	{"universal_carrier_anz" "Universal Carrier"}
     	{"np_t48_en" "M3 Halftrack QF 6-pdr"}
		{"bedford_anz" "Bedford OYD"}
		{"bedford_art_anz" "Bedford OYD"}
		{"bedford_eng_anz" "Bedford OYD"}
     	{"bofors_anz" "40mm M1 Bofors L/60"}
     	{"willysmb_anz" "Willys MB"}
     	{"gun_carrier_3_inch" "4.2 inch Mortar carrier"}
     	{"stag_hound" "Staghound QF 6-pdr"}
     	{"churchill_mk_v_cs" "Churchill Mk. VCS"}
     	{"m4a4_firefly_veteran" "Veteran M4A4 Firefly"}
     	{"sexton" "Sexton"}    	
		{"how_a(anz)" "BL 6\\26 cwt"}
		{"how_aa(anz)" "3.7-Inch QF AA"}
		{"how_b(anz)" "QF 25-pdr"}
          {"kangaroo" "Ram Kangaroo"}
          {"ram" "Ram Mk.II"}
	   	;----- ANZ