                {"8_kaska_soldat_ruminia" "Helmet"}
                {"fieldcap1_hun" "Cap"}
                {"fieldcap2_hun" "Cap"}
                {"fieldcap3_hun" "Cap"}
                {"helmet1_hun" "Helmet"}
                {"helmet2_hun" "Helmet"}
                {"helmet2_hun" "Helmet"}
                {"radiocap_hun" "Radio operator hat"}
                {"tankhelmet2_hun" "Helmet"}
                {"hungarian_36m" "36M Vecsey"}
                {"hungarian_42m" "42M Vecsey"}
                {"tankhelmet2_hun" "Helmet"}
		