		{"20mm_flak38" "20mm FlaK 38"}
		{"20mm_flak38_x4" "20mm FlaK 38"}
		{"20mm_kwk30" "20mm KwK 30"}
		{"20mm_mg151" "20mm MG 151"}
		{"20mm_mk10" "20mm Mk.10"}
		{"20mm_oerlikon" "20mm Oerlikon"}
		{"20mm_oerlikon_x2" "20mm Oerlikon"}
		{"20mm_tns" "20mm TNSh"}
		{"20mm_type2" "20mm Type 2"}
		{"37mm_61-k" "37mm 61K"}
		{"37mm_m3" "37mm M3"}
		{"37mm_m6" "37mm M6"}
		{"37mm_pak36" "37mm PaK 36"}
		{"37mm_type38" "37mm Type 38"}
		{"37mm_flak43" "37mm FlaK 43"}
		{"40mm_bofors" "40mm M1 Bofors L/60"}
		{"40mm_m19" "40mm M19"}
		{"40mm_oqf2pdr" "40mm QF 2pdr"}
		{"45mm_20k" "45mm 20K"}
		{"45mm_oqf2pdr" "45mm QF 2pdr"}
		{"47mm_40" "47mm L40"}
		{"47mm_type1" "47mm Type 1"}
		{"50mm_kwk38" "50mm KwK 38"}
		{"50mm_kwk39" "50mm KwK 39"}
		{"50mm_pak38" "50mm PaK 38"}
		{"57mm_type1" "50mm Type 1"}
		{"57mm_type2" "57mm Type 2"}
		{"57mm_type97" "57mm Type 97"}
		{"57mm_oqf" "57mm QF 6pdr"}
		{"57mm_zis2" "57mm ZIS-2"}
		{"57mm_zis4" "57mm ZIS-4"}
		{"75mm_kwk37" "75mm KwK 37"}
		{"75mm_kwk40" "75mm KwK 40"}
		{"75mm_kwk40(l48)" "75mm KwK 40 L/48"}
		{"75mm_kwk42" "75mm KwK 42"}
		{"75mm_m2" "75mm M2"}
		{"75mm_m2a" "75mm M2"}
		{"75mm_m3" "75mm M3"}
		{"75mm_m6" "75mm M6"}
		{"75mm_mk5" "75mm QF Mk.V"}
		{"75mm_pak39" "75mm PaK 39"}
		{"75mm_pak40" "75mm PaK 40"}
		{"75mm_stuk40" "75mm Stuk 40"}
		{"75mm_stuk42" "75mm Stuk 42"}
		{"75mm_type3" "75mm Type 3"}
		{"75mm_type5" "75mm Type 5"}
		{"75mm_type90" "75mm Type 90"}
		{"75mm_type99" "75mm Type 99"}
		{"76mm_f32" "76mm F32"}
		{"76mm_f34" "76mm F34"}
		{"76mm_kt26" "76mm KT-26"}
		{"76mm_l11" "76mm L11"}
		{"76mm_m1a2" "76mm M1A2"}
		{"76mm_m5" "76mm M5"}
		{"76mm_m7" "76mm M7"}
		{"76mm_mk4" "76mm Mk.IV"}
		{"76mm_zis3" "76mm ZIS-3"}
		{"76mm_zis5" "76mm ZIS-5"}
		{"77mm_hv" "77mm HV"}
		{"85mm_d5s" "85mm D5-S"}
		{"85mm_d5t" "85mm D5-T"}
		{"85mm_zis53" "85mm ZIS-53"}
		{"88mm_flak18" "88mm FlaK 18"}
		{"88mm_flak37" "88mm FlaK 37"}
		{"88mm_flak41" "88mm FlaK 41"}
		{"88mm_kwk36" "88mm KwK 36"}
		{"88mm_kwk36_veteran" "88mm KwK 36"}
		{"88mm_kwk43" "88mm KwK 43"}
		{"88mm_oqfmk2" "88mm OQF Mk. II"}
		{"88mm_pak43" "88mm PaK 43"}
		{"88mm_type99" "88mm Type 99"}
		{"90mm_m3" "90mm M3"}
		{"90mm_m15" "90mm M15"}
		{"93mm_vickers" "93mm 32pdr"}
		{"93mm_vickers_aa" "93mm 32pdr"}
		{"95mm_oqf" "95mm OQF"}
		{"100mm_d10c" "100mm D10S"}
		{"105mm_l31" "105mm L31"}
		{"105mm_m2a1" "105mm M2A1"}
		{"105mm_m4a3" "105mm M4"}
		{"105mm_stuh42" "105mm StuH 42"}
		{"105mm_type6" "105mm Type 6"}
		{"105mm_type91" "105mm Type 91"}
		{"120mm_l50" "120mm L/50"}
		{"120mm_type97" "120mm Type 97"}
		{"122mm_a19s" "122mm A19s"}
		{"122mm_d25" "122mm D25"}
		{"122mm_m30" "122mm M30"}
		{"122mm_m30s" "122mm M-30s"}
		{"128mm_pak44" "128mm PaK 44"}
		{"150mm_sfh18" "150mm sFH 18"}
		{"150mm_sfh18a" "150mm sFH 18"}
		{"150mm_type38" "150mm Type 38"}
		{"150mm_type96" "150mm Type 96"}
		{"152mm_bl6" "152mm BL 26cwt"}
		{"152mm_d1" "152mm D1"}
		{"152mm_m10t" "152mm ML20"}
		{"152mm_ml20a" "152mm ML20"}
		{"155mm_gpf" "155mm Howitzer"}
		{"155mm_m12" "155mm M12"}
		{"203mm_gun" "203mm mortar"}
		{"290mm_mortar" "290mm Spigot mortar"}
		{"380mm_rw61" "380mm RW61"}
		{"arl" "Missile"}
		{"bar" "B.A.R."}
		{"bazooka" "Bazooka M1A1"}
		{"besa" "B.E.S.A."}
		{"binocular" "Binocular"}
		{"bm8" "82mm BM-8 rockets"}
		{"bren" "Bren"}
		{"browning" ".50 cal M2HB"}
		{"browning_m19" ".30 cal M1919"}
		{"browning_m19a6" ".30 cal M1919 A6"}
		{"browning_x2" "2x .50 cal"}
		{"browning_x4" "4x .50 cal"}
		{"bomb_dropper" "Bomb"}
		{"bomb_dropper_il2" "Bomb"}
		{"boyes" "Boyes .55 Mk.I"}
		{"browning_stan" "Heavy MG"}
		{"calliope" "114mm M8 rockets"}
		{"colt" "Colt 45"}
		{"degtyarev_stan" "Heavy MG"}
		{"de_lisle" "De Lisle carbine"}
		{"doublebazooka" "2x Bazooka"}
		{"dp" "DP-27"}
		{"ds" "DS-39"}
		{"dshk" "DShK"}
		{"dt" "DT-29"}
		{"em2" "EM 2 sniper"}
		{"em3" "Lee-Enfield Mk.III"}
		{"em3_mark1" "EM-3 rifle grenade"}
		{"fg42" "FG-42"}
		{"flaergun" "Artillery signal gun"}
		{"flame_thrower" "Flamethrower"}
		{"flame_thrower_g" "Flamethrower"}
		{"flame_thrower_ssd" "Tank flamethrower"}
		{"flame_thrower_tank" "Tank flamethrower"}
		{"g41" "Karabiner 98k sniper"}
		{"g43" "G43"}
		{"g43_scope" "G43 Scope"}
		{"garand" "M1 Garand"}
		{"goliath" "Remote-controlled bomb"}
		{"hdm" "HDM OSS"}
		{"johnson" "M1941 Johnson Rifle"}
		{"johnson_m1941" "M1941 Johnson LMG"}
		{"katusha" "132mm BM-13 rockets"}
		{"lewis_gun" "Lewis Gun"}
		{"lm" "76mm RP-3 rockets"}
		{"luger" "Parabellum"}
		{"m18recoilless" "M18 recoilless rifle"}
		{"m1903" "M1903 Springfield"}
		{"m1903a4" "M1903A4 sniper"}
		{"m1_carbine" "M1A1 Carbine"}
		{"m12_shotgun" "M12 Shotgun"}
		{"m2_carbine" "M2 Carbine"}
		{"m3a" "M3A1"}
		{"m50reising" "M50 Reising"}
		{"mauzer" "Karabiner 98k"}
		{"maxim" "Maxim MG"}
		{"maxim_inv" "Maxim MG"}
		{"mg34" "MG 34"}
		{"mg34_tower" "MG 34"}
		{"mg34_x2" "2x MG 34"}
		{"mg37" "MG 37(t)"}
		{"mg42" "MG 42"}
		{"mg42_120" "MG 42"}
		{"mguncolt" "Colt MG"}
		{"mortar150" "150mm Type 97 mortar"}
		{"mosin" "Mosin"}
		{"mosin_s" "Mosin sniper"}
		{"mp28" "MP 28"}
		{"mp28_50" "MP 28"}
		{"mp3008" "MP 3008"}
		{"mp40" "MP 40"}
		{"mp41" "MP 41"}
		{"nagan" "Nagant"}
		{"nagan_pb" "Nagant with silencer"}
		{"nambu" "Type 14 Nambu"}
		{"nebel41" "150mm Nebelwerfer 41 rockets"}
		{"nebel42" "210mm Nebelwerfer 42 rockets"}
		{"owen_gun" "Owen Gun"}
		{"panzerfaust" "Panzerfaust 100"}
		{"panzershreck" "Panzerschreck"}
		{"panzerwerfer42" "150mm Nebelwerfer rockets"}
		{"piatrocket" "P.I.A.T. Mk.I"}
		{"ptrd" "14.5 PTRD"}
		{"ptrs" "14.5 PTRS"}
		{"pps43" "PPS-43"}
		{"ppsh" "PPSh"}
		{"ppsh41" "PPSh-41"}
		{"pzb39" "Pzb39"}
		{"searchlight" "Searchlight"}
		{"sg44" "StG 44"}
		{"sten" "Sten Mk.III"}
		{"sten_v" "Sten Mk.V"}
		{"sten_v_silencer" "Sten Mk.VI Silencer"}
		{"sks" "SKS"}
		{"svt40" "SVT-40"}
		{"t4_20cm" "200mm Type 4 rocket"}
		{"t4_30cm" "300mm Type 4 rocket"}
		{"t94" "Type 94"}
		{"thompson" "Thompson"}
		{"thompson_30" "Thompson 30"}
		{"thompson_m1928" "Thompson M1928"}
		{"torpedo" "Torpedo launcher"}
		{"tt" "TT"}
		{"tulip" "93mm Tulip rockets"}
		{"type100smg" "Type 100 SMG"}
		{"type1hmg" "Type 1 MG"}
		{"type2rifle" "Type 2 rifle"}
		{"type2smg" "Type 2 SMG"}
		{"type2_120mm" "120mm Type 2"}
		{"type4_200mm" "200mm Type 4"}
		{"type99lmg" "Type 99 MG"}
		{"type99rifle" "Type 99 rifle"}
		{"type99rifle_s" "Type 99 sniper"}
		{"type99rifle_at" "Type 99 at-rifle grenade"}
		{"type_4at" "Type 4 RPG"}
		{"type_96" "25mm Type 96"}
		{"type_97_antitank" "Type 97 AT-Rifle"}
		{"valter" "Walther"}
		{"vickers_k" "Vickers K (VGO)"}
		{"vickers_mgun" "Vickers"}
		{"webley" "Webley.45"}
		{"welrod" "Welrod"}
		{"werfer" "Mortar"}
		{"werfer42" "Mortar"} 
                {"37mm_m3_1" "37mm M3"}
                {"37mm_pak36_1" "37mm PaK 36"}
                {"40mm_oqf2pdr_1" "40mm QF 2pdr"}
                {"45mm_20k_1" "45mm 20K"}
                {"45mm_m42_1" "45mm m42"}
                {"47mm_type1_1" "47mm Type 1"}
                {"50mm_pak38_1" "50mm PaK 38"}
                {"57mm_oqf_1" "57mm QF 6pdr"}
                {"57mm_type1_1" "50mm Type 1"}
                {"57mm_zis2_1" "57mm ZIS-2"}
                {"75mm_kwk40(l48)_1" "75mm Pak 40"}
                {"75mm_pak39_1" "75mm PaK 39"}
                {"75mm_type5_1" "75mm Type 5"}
                {"75mm_type90_1" "75mm Type 90"}
                {"76mm_m1a2_1" "76mm M1A2"}
                {"76mm_m1a2_veteran" "76mm M1A2"}
                {"76mm_m5_1" "76mm M5"}
                {"76mm_m7_1" "76mm M7"}
                {"76mm_mk4_1" "76mm Mk.IV"}
                {"76mm_zis3_1" "76mm ZIS-3"}
                {"88mm_flak37_1" "88mm FlaK 37"}
                {"88mm_kwk43_1" "88mm KwK 43"}
                {"90mm_m3_1" "90mm M3"}
                {"93mm_vickers_1" "93mm 32pdr"}
                {"100mm_d10c_1" "100mm D10S"}
                {"150mm_sig33" "150mm Sigmars Hammer"}
                {"150mm_stuh43" "150mm Brumbar"}
                {"13mm_hotchkiss" "13mm hotchkiss"}
                {"13mm_hotchkiss_x2" "13mm hotchkiss x2"}
                {"20mm_s18_100" "Solothurn 20mm"}
                {"20mm_solothurn" "20mm_solothurn"}
                {"20mm_solothurn" "20mm aa"}
                {"25mm_1934" "Hotchkiss 25mm"}
                {"37mm_m3_1" "37 mm Gun M3"}
                {"37mm_mle1930" "Canon de 37mm"}
                {"37mm_pak36_1" "37mm PaK 36"}
                {"37mm_sa18" "37mm Puteaux SA 18"}
                {"37mm_sa18" "37mm Puteaux SA 38"}
                {"40mm_42m" "40mm 42m"}
                {"40mm_bofors_nimrod" "40mm M1 Bofors L/60"}
                {"40mm_oqf2pdr_1" "45mm QF 2pdr"}
                {"45mm_20k_1" "45mm 20K"}
                {"45mm_m42_1" "45mm M-42"}
                {"47mm_sa34" "47mm SA34 L/30"}
                {"47mm_sa35" "47mm SA 35"}
                {"47mm_sa1937" "47mm SA 37"}
                {"47mm_sa1937_pak" "47mm SA 37"}
                {"47mm_type1_1" "47mm Type 1"}
                {"50mm_pak38_1" "50mm PaK 38"}
                {"57mm_oqf_1" "57mm QF 6pdr"}
                {"57mm_revolver" "57mm QF 6pdr"}
                {"57mm_type1_1" "50mm Type 1"}
                {"57mm_zis2_1" "57mm ZIS-2"}
                {"75mm_41m" "75mm 41M"}
                {"75mm_43m" "75mm 43M"}
                {"75mm_kwk40(l48)_1" "75mm KwK 40 L/48"}
                {"75mm_pak39_1" "75mm PaK 39"}
                {"75mm_sa35" "75mm SA35"}
                {"75mm_sa35_ter" "75mm SA35"}
                {"75mm_shneider" "75mm Shneider"}
                {"75mm_type5_1" "75mm Type 5"}
                {"75mm_type90_1" "75mm Type 90"}
                {"75mm_vickers" "75mm Vickers"}
                {"76mm_m1a2_1" "76mm M1A2"}
                {"76mm_m1a2_veteran" "76mm M1A2"}
                {"76mm_m5_1" "76mm M5"}
                {"76mm_m7_1" "76mm M7"}
                {"76mm_m1936_1" "76mm F-22"}
                {"76mm_mk4_1" "76mm Mk.IV"}
                {"76mm_zis3_1" "76mm ZIS-3"}
                {"88mm_flak37_1" "88mm FlaK 37"}
                {"88mm_kwk43_1" "88mm KwK 43"}
                {"88mm_type99" "88mm Type 99"}
                {"90mm_d915" "90mm D915"}
                {"90mm_dca45" "90mm DCA45"}
                {"90mm_m3_1" "90mm M3"}
                {"93mm_vickers_1" "93mm 32pdr"}
                {"100mm_d10c_1" "100mm D10C"}
                {"100mm_sa47" "100mm SA47"}
                {"105mm_40_43m" "105mm 40/43M L20.5"}
                {"105mm_l13s" "105mm 105mm L31"}
                {"150mm_sig33" "SIG 33"}
                {"150mm_stuh43" "105mm StuH 42"}