                {"mas38" "MAS-38"}
                {"lebel_1886m93sc" "Mle 1886 Sniper"}
                {"lebel_m1886" "Mle 1886"}
                {"lebel_m1886_m" "Mle 1886 M"}
                {"Reibel" "Reibel MG"}
                {"hotchkiss" "Hotchkiss M1914"}
                {"fm_24-29" "FM 24/29"}
                {"fm_24-29_t" "FM 24/29"}
                {"browning_wz28" "Browning wz. 1928"}
                {"modele_1935" "Modèle 1935"}
                {"karabinek_wz29" "Karabinek w29"}
                {"karabinek_wz98" "Karabinek w98"}
		