				{"r12_hun" "BMW R12"}
		{"stoewer_t40_kfz4" "Stoewer T40"}
		{"np_sdkfz251_hun" "SdKfz 251/1"}
		{"mercedes_hun" "Mercedes-Benz L3000"}
		{"mercedes_hun_art" "Mercedes-Benz L3000"}
		{"mercedes_hun_eng" "Mercedes-Benz L3000"}
		{"mg13_stan" "Heavy MG"}
		{"13mm_hotchkiss_hun" "Hotchkiss M1929"}
		{"sgrw42_hun" "sGrW 34 mortar"}
		{"pak36_hun" "PaK 36"}
		{"pak38_hun" "PaK 38"}
		{"pak40_hun" "PaK 40"}
		{"how_aa(hun)" "40mm Bofors"}
		{"how_a(hun)" "sFH 18"}
		{"how_b(hun)" "le. FH 18 M"}
				{"how_aa(hun2)" "40mm Bofors"}
		{"how_a(hun2)" "sFH 18"}
		{"how_b(hun2)" "le. FH 18 M"}
		{"l335_hun" "L3/35"}
		{"csaba39m" "Csaba 39M"}
		{"csaba40m" "Csaba 40M"}
		{"toldi1" "Toldi I 38M"}
		{"pzkpfw38t_hun" "PzKpfw 38(t) Ausf.B"}
		{"toldi2" "Toldi II 38M"}
		{"nimrod" "Nimrod 40M"}
		{"zrinyi2" "Zrinyi II 43M"}
				{"zrinyi22" "Zrinyi II 43M"}
		{"zrinyi1" "Zrinyi I 43M"}
				{"zrinyi12" "Zrinyi I 43M"}
		{"turan3" "Turan III 40M"}
		{"turan2" "Turan II 40M"}
		{"turan1" "Turan I 40M"}
		{"pz4e_hun" "Pz IV Ausf. D"}
		{"pz4f_hun" "Pz IV Ausf. F2"}
		{"hetzer_hun2" "Hetzer"}
				{"hetzer_hun" "Hetzer"}
		{"marder139" "Marder III Ausf. M"}
				{"marder1392" "Marder III Ausf. M"}
		{"tas_44m" "Tas 44M"}
		{"tas_44td" "Tas 44M TD"}
		{"tas_44td2" "Tas 44M TD"}
        {"solothurn_hun" "Solothurn S-18/1000"}
        {"np_sig33 " "15 cm sIG 33"}
                