        {"155gpf" "155 GPF mle.1917"}
		{"203b4" "203mm B-4M"}
		{"20mm_u_boat" "AA gun"}
		{"20mm_type97" "20mm Type 97"}
		{"50_browning_m2hb" ".50cal M2HB"}
		{"88mm_u_boat" "FlaK 41"}
		{"achilles" "Achilles 1C"}
		{"air-bag" "Boat"}
		{"archer" "Archer"}
		{"armor_barge_cs1" "Barge"}
		{"armor_barge_cs2" "Barge"}
		{"armored_locomotive" "Locomotive"}
		{"arl44" "ARL-44"}		
        {"ba11" "BA-11"}
		{"ba64" "BA-64"}
		{"bedford" "Bedford OYD"}
		{"bedford_art" "Bedford OYD"}
		{"bedford_eng" "Bedford OYD"}
		{"bedford_inf" "Bedford OYD"}
		{"bf109g" "BF-109 G-16"}
		{"bishop" "Mk I Bishop"}
		{"bk1124_k" "Ship"}
		{"bl6" "BL 6\" 26 cwt"}
		{"black_prince" "Black Prince"}
		{"blitz3_6" "Opel Blitz 3.6"}
		{"blitz3_6art" "Opel Blitz 3.6"}
		{"blitz3_6eng" "Opel Blitz 3.6"}
		{"blitz3_6f" "Fuel truck"}
		{"blitz3_6inf" "Opel Blitz 3.6"}
		{"blitz3_6m" "Ambulance truck"}
		{"bm13" "BM-13 Katyusha"}
		{"bm_8_24" "BM-8-24"}
		{"bm37" "BM-37 mortar"}
		{"bofors" "40mm M1 Bofors L/60"}
		{"box1" "Big box"}
		{"box2" "Small box"}
		{"boxes1" "Pile of boxes"}
		{"browning_stan" "Heavy MG"}
		{"browning_stan_fix" "Heavy MG"}
		{"brummbar" "Brummbar"}
        {"bs3" "BS-3"}
        {"bt7b" "BT-7"}
		{"bt7a" "BT-7a"}
		{"centurion" "Centurion Mk.II"}
		{"chicken" "Chicken"}
		{"chi-ha120" "Chi-Ha 120"}
		{"chi-ha47" "Chi-Ha 47"}
		{"chi-ha57" "Chi-Ha 57"}
        {"ta-se" "Ta-Se"}
        {"challenger_a30" "Challenger (A30)"}
		{"chi-he" "Chi-He"}
		{"chi-nu" "Chi-Nu"}
		{"chi-nu_kai" "Chi-Nu Kai"}
		{"chi-ri" "Chi-Ri"}
		{"chi-to" "Chi-To"}
		{"churchill_avre" "Churchill AVRE"}
		{"churchill_crocodile" "Churchill Crocodile"}
		{"churchill_mk_vii" "Mk.IV Churchill"}
		{"cistern" "Tank wagon"}
		{"cometa34" "Comet I (A34)"}
		{"cow" "Cow"}
		{"crane_rail" "Crane"}
		{"crane_rail1" "Rail crane"}
		{"crane_m" "Crane"}
		{"crusaderaa2" "Crusader AAII"}
		{"crusaderaa1" "Crusader AA"}
		{"crusaderi" "Mk.I Crusader "}
		{"crusaderii" "Mk.II Crusader "}
		{"crusaderics" "Mk.ICS Crusader"}
		{"d1" "D1"}
		{"degtyarev_stan" "Heavy MG"}
		{"degtyarev_stan_fix" "Heavy MG"}
		{"destroyer_k" "Ship"}
		{"dodge" "Dodge WC-56"}
		{"dodgewc55" "Dodge WC-55"}
		{"elefant" "Elefant"}
		{"flak18" "FlaK 18"}
		{"flak37" "FlaK 37"}
		{"flak38" "FlaK 38"}
		{"flak38_wheeled" "FlaK 38"}
		{"flak-38-1" "FlaK 38"}
		{"flak41" "FlaK 41"}
		{"gaz67" "GAZ-67"}
		{"gaz67b" "GAZ-67B"}
		{"gmc" "GMC CCKW"}
		{"gmc_art" "GMC CCKW"}
		{"gmc_cckw" "GMC CCKW-353"}
		{"gmc_eng" "GMC CCKW"}
		{"gmc_fuel" "GMC Refueller"}
		{"gmc_inf" "GMC CCKW"}
        {"grant_m3" "M3 Lee"}
		{"hamilcar" "G.A.L.49 Hamilcar"}
		{"ha-go" "Ha-Go"}
		{"ha-to" "Ha-To"}
		{"hd" "Harley Davidson"}
		{"hetzer" "Hetzer"}
		{"horch" "Horch"}
		{"how_a(eng)" "BL 6\\26 cwt"}
		{"how_aa(eng)" "3.7-Inch QF AA"}
		{"how_b(eng)" "QF 25-pdr"}
		{"how_a(ger)" "sFH 18"}
		{"how_aa(ger)" "FlaK 37"}
		{"how_b(ger)" "le. FH 18 M"}
		{"how_a(jap)" "150mm Type 96"}
		{"how_aa(jap)" "75mm Type 4 AA Gun"}
		{"how_b(jap)" "105mm Type 91"}
		{"how_a(rus)" "D1"}
		{"how_aa(rus)" "61-K M1939"}
		{"how_b(rus)" "M-30"}
		{"how_a(usa)" "M114"}
		{"how_aa(usa)" "40mm M1 Bofors L/60"}
		{"how_b(usa)" "M2A1 L"}
		{"ho-ha3mgun" "Ho-Ha"}
		{"ho-i" "Ho-I"}
		{"ho-ni1" "Ho-Ni 1"}
		{"ho-ni2" "Ho-Ni 2"}
		{"ho-ni_3" "Ho-Ni 3"}
		{"ho-ri" "Ho-Ri 2"}
		{"ho-ri_1" "Ho-Ri 1"}
		{"ho-ro" "Ho-Ro"}
		{"hummel" "Hummel"}
		{"humber" "Humber"}
		{"il-2" "IL-2"}
		{"is1" "IS-1"}
		{"is122" "IS-122"}
		{"is2" "IS-2M"}
		{"is3" "IS-3"}
		{"isu122" "ISU-122"}
		{"isu152" "ISU-152"}
		{"isuzutx40" "Isuzu"}
		{"isuzutx40art" "Isuzu"}
		{"isuzutx40_aa" "Isuzu AA"}
		{"isuzutx40_eng" "Isuzu"}
		{"isuzutx40_inf" "Isuzu"}
		{"isuzutx40_mort" "Isuzu mortar"}
		{"jagdpanther" "Jagdpanther"}
		{"jagdpanzer_iv" "Jagdpanzer IV"}
		{"jagdtiger" "Jagdtiger"}
		{"ju-52" "JU-52"}
		{"ju-87" "JU-87 A-1"}
		{"k18" "K18"}
		{"k61" "61-K"}
		{"k61_fix" "61-K"}
		{"ke-nu" "Ke-Nu"}
		{"dshk_stan" "DShK Heavy MG"}
		{"kubel" "Kubel VW82"}
		{"kubel_mgun" "Kubel VW82"}
		{"kv1" "KV-1"}
		{"kv2" "KV-2"}
		{"kv85" "KV-85"}
		{"land_mattress" "Land Mattress"}
		{"land_mattress(eng)" "Land Mattress"}
		{"lci(l)" "LCI(L)"}
		{"lcvp" "Landing craft"}
		{"lefh18" "le. FH 18 M"}
		{"lg_40" "7.5 cm Leichtgeschutz 40"}
		{"lvt4" "LVT(A)-4"}
		{"marder_3h" "Marder III Ausf. H"}
		{"m10wolverine" "M10 Wolverine"}
		{"m114" "M114"}
		{"m12gmc" "M12 gun motor carriage"}
		{"m16" "M16"}
		{"m18" "M18 Hellcat"}
		{"m19" "M19"}
		{"m1mortar" "M1 mortar"}
		{"m1_57mm" "M1 AT gun"}
		{"m20" "M20"}
		{"m24" "M24 Chaffee"}
		{"m26e4" "M26 E4 'Super Pershing'"}
		{"m26_pershing" "M26 Pershing"}
	    {"m26_pershing2" "M26 Pershing"}
		{"m2a1l" "M2A1 L"}
		{"m3" "M5A1"}
		{"m3_usa" "M3A1"}
		{"m3_eng" "M5A1"}
		{"m30_1938" "M-30"}
		{"m30kangaroo" "Priest Kangaroo"}
		{"m36" "M36 Slugger"}
		{"m37" "M-37"}
        {"m3cannon" "M3 AT gun"}
		{"m42" "M-42"}
        {"m4a3c" "M4A3 Calliope"}
		{"m4a3e2_jumbo" "M4A3E2 Jumbo"}
		{"m4a3e2_jumbo_76" "M4A3E2(76)W Jumbo"}
		{"m4a3e8" "M4A3E8(76)W Sherman"}
        {"m4a3e8_fury" "Veteran M4A3E8(76)W Sherman"}
		{"m4a3m" "M4A3 Crab"}
		{"m4a3m_eng" "M4A3 Crab"}
		{"m4a3vc" "M4A4 VC Firefly"}
		{"m4a3_75" "M4A3 Sherman"}
		{"m4a3_752" "M4A3 Sherman"}
		{"m4a3_105" "M4A3(105) Sherman"}
		{"m4a3_zippo" "M4A3R2 Croc"}
		{"m4a4" "M4A4"}
		{"m4a1_eng" "Grizzly I "}
		{"m4a4_firefly" "M4A4 Firefly"}
		{"m4a4_tulip" "M4A4 Tulip"}
		{"m5" "M5 AT gun"}
		{"m56" "M56 Skropion"}
		{"m5a1" "M5A1 Stuart"}
		{"m7" "M7 Priest"}
		{"m72" "M-72"}
		{"m7_eng" "M7 Priest"}
		{"m8" "M8 Scott"}
		{"m8a1" "M8A1 Scott"}
		{"m8grayhound" "M8 Greyhound"}
		{"m8_howitzer" "M8"}
		{"maxim" "Maxim MG"}
		{"maxim_quad" "Maxim AA"}
		{"maxson" "M45 Maxson AA"}
		{"maxson_fix" "M45 Maxson AA"}
		{"mg1_ju52" "Mounted MG"}
		{"mg2_ju52" "Mounted MG"}
		{"mg34_tower" "Heavy MG"}
		{"mg42_stan" "Heavy MG"}
		{"mg42_stan_fix" "Heavy MG"}
		{"mk10" "MK10"}
		{"mk2a" "Mk.IIA Matilda"}
		{"mk2daimler" "Daimler AC Mk.I"}
		{"mk3" "Mk.III Valentine"}
		{"mk4" "Mk.IV Churchill"}
		{"mk6" "Mk.VI Crusader"}
		{"mk7" "Mk.VII Tetrarch"}
		{"mk7_littlejohn" "Mk.VII Tetrarch Littlejohn"}
		{"cromwell_mk_vii" "Mk.VIII Cromwell"}
		{"cromwell_mk_vi" "Mk.VIII Cromwell 95mm"}
		{"ml3" "ML3 Mk.II mortar"}
		{"nashorn" "Nashorn"}
        {"na-to" "Na-To"}          
		{"nebelwerfer41" "Nebelwerfer 41"}
		{"nebelwerfer42" "Nebelwerfer 42"}
		{"np_type95" "Type 95"}
		{"np_sdkfz234_4" "SdKfz 234/4 Pakwagen"}
		{"np_sdkfz8_flak" "8.8 cm Flak.37 sfl"}
        {"oerlikon" "Oerlikon 20mm"}
		{"oerlikon_fix" "Oerlikon 20mm"}
		{"ostwind" "Ostwind"}
		{"ot34_2" "O-34/76"}
		{"pak36" "PaK 36"}
		{"pak38" "PaK 38"}
		{"pak40" "PaK 40"}
		{"pak40_platform" "PaK 40"}
		{"pak43" "PaK 43"}
		{"pak47" "47mm Type 1"}
		{"pak57" "57mm Type 2"}
		{"panzerjager" "Panzerjager I"}
		{"passengervan" "Passenger car"}
		{"pdr25" "QF 25-pdr"}
		{"pg1" "Motor boat"}
		{"platform" "Platform car"}
		{"platform_can" "Platform car"}
		{"platform_gun" "Platform car"}
		{"pz1" "Flakpanzer I"}
		{"pz1b" "PzKpfw I Ausf.B"}
		{"pz2f" "PzKpfw II Ausf.C"}
		{"pz2l" "PzKpfw II Luchs"}
		{"pz3" "PzKpfw III Ausf.J"}
		{"pz3e" "PzKpfw III Ausf.E"}
        {"pz3f" "PzKpfw III Ausf.F"}
		{"pz3m" "Pz III Sapper"}
		{"pz3_m" "PzKpfw III Ausf.M"}
		{"pz3_m_flamer" "PzKpfw III Flamer"}
		{"pz3n" "PzKpfw III Ausf.N"}
		{"pz4d" "PzKpfw IV Ausf.D"}
		{"pz4g" "PzKpfw IV Ausf.F2"}
		{"pz4g2" "PzKpfw IV Ausf.G"}
		{"pz4h" "PzKpfw IV Ausf.H"}
		{"pz5" "PzKpfw V Panther"}
		{"pz5g" "PzKpfw V Panther Ausf.G"}
		{"pz5a" "PzKpfw V Panther Ausf.D"}
		{"pz6b" "PzKpfw VI Kingtiger"}
		{"pz6bh" "PzKpfw VI Kingtiger"}
		{"pz6e" "PzKpfw VI Tiger"}
		{"pz_turret" "Pz Turret"}
		{"p-51mustang" "P51 Mustang"}
		{"qf17" "QF 17-pdr"}
		{"qf2" "QF 2-pdr"}
		{"qf6" "QF 6-pdr"}
		{"r12" "BMW  R12"}
		{"s100_k" "Ship"}
		{"searchlight" "Search light"}
		{"searchlight2" "Search light"}
		{"sdkfz222" "SdKfz 222"}
		{"sdkfz223" "SdKfz 223"}
		{"sdkfz232" "SdKfz 232"}
		{"sdkfz234" "SdKfz 234 Puma"}
		{"sdkfz251_1" "SdKfz 251/1"}
		{"sdkfz303" "SdKfz 303 'Goliath'"}
		{"sdkfz4" "Panzerwerfer"}
		{"sfh18" "sFH 18"}
		{"sgrw42" "sGrW 34 mortar"}
		{"sig33" "siG 33"}
		{"ss-d" "SS-D"}
		{"staghound" "Staghound"}
		{"staghound_e1" "Staghound Tulip"}
		{"steam_locomotive" "Locomotive"}
		{"stug3g" "StuG III Ausf.G"}
		{"stug4g" "StuG IV Ausf.G"}
		{"stuh42" "StuH 42"}
		{"sturmtiger" "Sturmtiger"}
		{"su122" "SU-122"}
		{"su76" "SU-76"}
		{"su85" "SU-85"}
		{"su85m" "SU-85M"}
		{"su100" "SU-100"}
		{"su100m1" "SU-100M1"}
        {"t20" "T20 \"Komsomolets\" tractor"}
		{"t26" "T-26"}
		{"t29" "T29"}
		{"t34_0" "T-34/76 L-11"}
		{"t34_1" "T-34/57"}
		{"t34_2" "T-34/76 F-34"}
		{"t34_3c" "T-34/85"}
		{"t34m" "T-34 Sapper"}
		{"t-38" "T-38"}
        {"t60" "T-60"}
		{"t70" "T-70"}
		{"t90_75m" "75mm Type 90"}
		{"t91_105m" "105mm Type 91"}
		{"t96_150mm" "Type 96"}
		{"ta-se" "Ta-Se"}
		{"te-ke" "Type 97"}
        {"tendor" "Tender"}
		{"tradevan" "House car"}
		{"tradevan_big" "House car"}
		{"tradevan_explosive" "Explosive car"}
		{"tramway" "Tram"}
		{"tramway_driveable" "Tram"}
		{"type1hmg_stan" "Heavy MG"}
		{"type1hmg_stan_fix" "Heavy MG"}
		{"type2_20mm" "20mm Type 2"}
		{"type2_20mm_stand" "20mm Type 2"}
		{"type4_200mm" "200mm Type 4"}
		{"type4_75mm" "75mm Type 4"}
		{"type89" "Chi-Ro"}
		{"type96_150mm" "150mm Type 96"}
		{"type93scout" "Type 92"}
		{"type94" "Type 94 mortar"}
		{"type97" "Type 97"}
		{"type_97_150mm" "150mm Type 97 mortar"}
		{"universal" "Universal-1"}
		{"universal_carrier" "Bren carrier"}
		{"u-boat" "U-boat"}
		{"veteran_tiger" "Veteran Tiger"}
		{"vergeltungswaffe1" "Vengence Weapon 1"}
		{"vickers" "3.7-Inch QF AA Mk.II"}
		{"vickers_mgun" "Heavy MG"}
		{"vickers_stan" "Heavy MG"}
		{"vickers_stan_fix" "Heavy MG"}
		{"welberwind" "Wirbelwind"}
		{"wespe" "Wespe"}
		{"willysat" "Willys AT"}
		{"willysmb" "Willys MB"}
		{"willysmb_eng" "Willys MB"}
		{"ya5_k" "Ship"}
		{"zis2" "ZIS-2"}
		{"zis3" "ZiS-3"}
		{"zis5" "ZiS-5"}
		{"zis5art" "ZiS-5"}
		{"zis5eng" "ZiS-5"}
		{"zis5inf" "ZiS-5"}
		{"zsu37" "ZSU-37"}
		{"zis_30" "ZiS-30"}
	   	;----- VAN