		{"ita_basco" "Basco Xa MAS"}
		{"ita_bustina" "Bustina"}
		{"ita_M33_alpino" "Elmetto M33 (alpino)"}
		{"ita_fieldcap_sscam" "Berretto da campo SS"}
		{"ita_M33_fante" "Elmetto M33"}
		{"ita_M42_para_cam" "Elmetto M42/60"}
		{"ita_paradropammo" "Signal - ammo paradrop"}
		{"ita_paradropammo_heavy" "Signal - heavy ammo paradrop"}
		{"knife_ita" "Pugnale"}
		{"balloon_ita" "Italian Flame Balloon"}
		{"breda35" "Breda Mod.35"}
		{"OTO_mod35" "Bomba a Mano Mod. 35 O.T.O."}
		{"breda42at" "Breda Mod.42 anticarro"}
		{"ccm34smoke" "CCM34 fumogena"}
		{"oto42flam" "OTO Mod.42 incendiaria"}
		{"srcm35" "SRCM Mod.35"}