        {"ap_miners(eng)" "Combat engineers (infantry)"}
		{"ap_miners(ger)" "Combat engineers (infantry)"}
		{"ap_miners(jap)" "Combat engineers (infantry)"}
		{"ap_miners(rus)" "Combat engineers (infantry)"}
		{"ap_miners(usa)" "Combat engineers (infantry)"}
		{"ap_miners(hun)" "Combat engineers (infantry)"}
		{"ap_miners(fra)" "Combat engineers (infantry)"}
		{"ap_miners(fin)" "Combat engineers (infantry)"}
		{"ap_miners(ita)" "Combat engineers (infantry)"}
		{"ap_miners(chn)" "Combat engineers (infantry)"}
		{"ap_miners(anz)" "Combat engineers (infantry)"}		
        {"at_miners(eng)" "Combat engineers (vehicle)"}
		{"at_miners(ger)" "Combat engineers (vehicle)"}
		{"at_miners(jap)" "Combat engineers (vehicle)"}
		{"at_miners(rus)" "Combat engineers (vehicle)"}
		{"at_miners(usa)" "Combat engineers (vehicle)"}
		{"at_miners(hun)" "Combat engineers (vehicle)"}
		{"at_miners(fra)" "Combat engineers (vehicle)"}
		{"at_miners(fin)" "Combat engineers (vehicle)"}
		{"at_miners(ita)" "Combat engineers (vehicle)"}
		{"at_miners(chn)" "Combat engineers (vehicle)"}
		{"at_miners(anz)" "Combat engineers (vehicle)"}
		{"at_rifles(eng)" "AT-Rifle infantry"}
		{"at_rifles(ger)" "AT-Rifle infantry"}
		{"at_rifles(jap)" "AT-Rifle infantry"}
		{"at_rifles(rus)" "AT-Rifle infantry"}
		{"at_rifles(hun)" "AT-Rifle infantry"}
		{"at_rifles(fra)" "AT-Rifle infantry"}
		{"at_rifles(fin)" "AT-Rifle infantry"}
		{"at_rifles(ita)" "AT-Rifle infantry"}
		{"at_rifles(chn)" "AT-Rifle infantry"}
		{"at_rifles(anz)" "AT-Rifle infantry"}
		{"bazookers(eng)" "AT infantry"}
		{"bazookers(ger)" "AT infantry"}
		{"bazookers(jap)" "AT infantry"}
		{"bazookers(rus)" "AT infantry"}
		{"bazookers(usa)" "AT infantry"}
		{"bazookers(hun)" "AT infantry"}
		{"bazookers(fra)" "AT infantry"}
		{"bazookers(fin)" "AT infantry"}
		{"bazookers(ita)" "AT infantry"}
		{"bazookers(chn)" "AT infantry"}
		{"bazookers(anz)" "AT infantry"}
		{"elites(eng)" "Commandos"}
		{"elites(ger)" "Paratroopers"}
		{"elites(jap)" "Paratroopers"}
		{"elites(rus)" "Marines"}
		{"elites(usa)" "Airborne"}
		{"elites(hun)" "Paratroopers"}
		{"elites(fra)" "Foreign Legion"}
		{"elites(fin)" "Kaukopartio"}
		{"elites(ita)" "Paracadutisti"}
		{"elites(chn)" "Foreign-trained infantry"}
		{"elites(anz)" "Diggers"}
		{"flamers(eng)" "Flamethrower infantry"}
		{"flamers(ger)" "Flamethrower infantry"}
		{"flamers(jap)" "Flamethrower infantry"}
		{"flamers(rus)" "Flamethrower infantry"}
		{"flamers(usa)" "Flamethrower infantry"}
		{"flamers(hun)" "Flamethrower infantry"}
		{"flamers(fra)" "Flamethrower infantry"}
		{"flamers(fin)" "Flamethrower infantry"}
		{"flamers(ita)" "Flamethrower infantry"}
		{"flamers(chn)" "Flamethrower infantry"}
		{"flamers(anz)" "Flamethrower infantry"}
		{"home_guards(eng)" "Militia"}
		{"home_guards(ger)" "Volkssturm"}
		{"home_guards(jap)" "Recruits"}
		{"home_guards(rus)" "Partisan"}
		{"home_guards(usa)" "Conscripts"}
		{"home_guards(hun)" "Home Guards"}
		{"home_guards(fra)" "Resistance"}
		{"home_guards(fin)" "Reservists"}
		{"home_guards(ita)" "Milizia"}
		{"home_guards(chn)" "Peasants"}
		{"home_guards(anz)" "Conscripts"}
		{"kamikazes(jap)" "Kamikaze"}
		{"mgs2(eng)" "Machine gunner"}
		{"mgs2(ger)" "Machine gunner"}
		{"mgs2(jap)" "Machine gunner"}
		{"mgs2(rus)" "Machine gunner"}
		{"mgs2(usa)" "Machine gunner"}
		{"mgs2(hun)" "Machine gunner"}
		{"mgs2(fra)" "Machine gunner"}
		{"mgs2(fin)" "Machine gunner"}
		{"mgs2(ita)" "Machine gunner"}
		{"mgs2(chn)" "Machine gunner"}
		{"mgs2(anz)" "Machine gunner"}
		{"officers(eng)" "Officer"}
		{"officers(ger)" "Officer"}
		{"officers(jap)" "Officer"}
		{"officers(rus)" "Officer"}
		{"officers(usa)" "Officer"}
		{"officers(hun)" "Officer"}
		{"officers(fra)" "Officer"}
		{"officers(fin)" "Officer"}
		{"officers(ita)" "Officer"}
		{"officers(chn)" "Officer"}
		{"officers(anz)" "Officer"}
		{"riflemans(eng)" "Regular infantry"}
		{"riflemans(ger)" "Regular infantry"}
		{"riflemans(jap)" "Regular infantry"}
		{"riflemans(rus)" "Regular infantry"}
		{"riflemans(usa)" "Regular infantry"}
		{"riflemans(hun)" "Regular infantry"}
		{"riflemans(fra)" "Regular infantry"}
		{"riflemans(fin)" "Regular infantry"}
		{"riflemans(ita)" "Regular infantry"}
		{"riflemans(chn)" "Regular infantry"}
		{"riflemans(anz)" "Regular infantry"}
		{"riflemans2(eng)" "Rifleman"}
		{"riflemans2(ger)" "Rifleman"}
		{"riflemans2(jap)" "Rifleman"}
		{"riflemans2(rus)" "Rifleman"}
		{"riflemans2(usa)" "Rifleman"}
		{"riflemans2(hun)" "Rifleman"}
		{"riflemans2(fra)" "Rifleman"}
		{"riflemans2(fin)" "Rifleman"}
		{"riflemans2(ita)" "Rifleman"}
		{"riflemans2(chn)" "Rifleman"}
		{"riflemans2(anz)" "Rifleman"}
		{"sappers(eng)" "Mine disposal experts"}
		{"sappers(ger)" "Mine disposal experts"}
		{"sappers(jap)" "Mine disposal experts"}
		{"sappers(rus)" "Mine disposal experts"}
		{"sappers(usa)" "Mine disposal experts"}
		{"sappers(hun)" "Mine disposal experts"}
		{"sappers(fra)" "Mine disposal experts"}
		{"sappers(fin)" "Mine disposal experts"}
		{"sappers(ita)" "Mine disposal experts"}
		{"sappers(chn)" "Mine disposal experts"}
		{"sappers(anz)" "Mine disposal experts"}
		{"smgs(eng)" "Assault infantry"}
		{"smgs(ger)" "Assault infantry"}
		{"smgs(jap)" "Assault infantry"}
		{"smgs(rus)" "Assault infantry"}
		{"smgs(usa)" "Assault infantry"}
		{"smgs(hun)" "Assault infantry"}
		{"smgs(fra)" "Assault infantry"}
		{"smgs(fin)" "Assault infantry"}
		{"smgs(ita)" "Assault infantry"}
		{"smgs(chn)" "Assault infantry"}
		{"smgs(anz)" "Assault infantry"}
		{"smgs2(eng)" "SMG"}
		{"smgs2(ger)" "SMG"}
		{"smgs2(jap)" "SMG"}
		{"smgs2(rus)" "SMG"}
		{"smgs2(usa)" "SMG"}
		{"smgs2(hun)" "SMG"}
		{"smgs2(fra)" "SMG"}
		{"smgs2(fin)" "SMG"}
		{"smgs2(ita)" "SMG"}
		{"smgs2(chn)" "SMG"}
	    {"smgs2(anz)" "SMG"}
        {"smgs3(eng)" "Demolition specialists"}
		{"smgs3(ger)" "Demolition specialists"}
		{"smgs3(jap)" "Demolition specialists"}
		{"smgs3(rus)" "Demolition specialists"}
		{"smgs3(usa)" "Demolition specialists"}
		{"smgs3(hun)" "Demolition specialists"}
		{"smgs3(fra)" "Demolition specialists"}
		{"smgs3(fin)" "Demolition specialists"}
		{"smgs3(ita)" "Demolition specialists"}
		{"smgs3(chn)" "Demolition specialists"}
	    {"smgs3(anz)" "Demolition specialists"}
        {"elites2(eng)" "Veteran rifleman"}
		{"elites2(ger)" "Veteran rifleman"}
		{"elites2(jap)" "Veteran rifleman"}
		{"elites2(rus)" "Veteran rifleman"}
		{"elites2(usa)" "Veteran rifleman"}
		{"elites2(hun)" "Veteran rifleman"}
		{"elites2(fra)" "Veteran rifleman"}
		{"elites2(fin)" "Veteran rifleman"}
		{"elites2(ita)" "Veteran rifleman"}
		{"elites2(chn)" "Veteran rifleman"}
	    {"elites2(anz)" "Veteran rifleman"}
        {"snipers(eng)" "Sniper"}
		{"snipers(ger)" "Sniper"}
		{"snipers(jap)" "Sniper"}
		{"snipers(rus)" "Sniper"}
		{"snipers(usa)" "Sniper"}
		{"snipers(hun)" "Sniper"}
		{"snipers(fra)" "Sniper"}
		{"snipers(fin)" "Sniper"}
		{"snipers(ita)" "Sniper"}
		{"snipers(chn)" "Sniper"}
		{"snipers(anz)" "Sniper"}
		{"snipers_d(eng)" "Sniper"}
		{"snipers_d(ger)" "Sniper"}
		{"snipers_d(jap)" "Sniper"}
		{"snipers_d(rus)" "Sniper"}
		{"snipers_d(usa)" "Sniper"}
		{"snipers_d(hun)" "Sniper"}
		{"snipers_d(fra)" "Sniper"}
		{"snipers_d(fin)" "Sniper"}
		{"snipers_d(ita)" "Sniper"}
		{"snipers_d(chn)" "Sniper"}
		{"snipers_d(anz)" "Sniper"}
		{"shotguns(usa)" "Shotgunners"}
		{"stormtroopers(eng)" "SAS"}
		{"stormtroopers1(eng)" "Elite marksmen"}
		{"stormtroopers2(eng)" "Elite AT infantry"}
		{"stormtroopers3(eng)" "Elite support infantry"}
        {"stormtroopers4(eng)" "Elite CQB infantry"}
		{"stormtroopers(ger)" "Panzergrenadiere"}
		{"stormtroopers1(ger)" "Elite marksmen"}
		{"stormtroopers2(ger)" "Elite AT infantry"}
		{"stormtroopers3(ger)" "Elite support infantry"}
		{"stormtroopers4(ger)" "Elite CQB infantry"}
        {"stormtroopers(jap)" "SNLF"}
		{"stormtroopers1(jap)" "Elite marksmen"}
		{"stormtroopers2(jap)" "Elite AT infantry"}
		{"stormtroopers3(jap)" "Elite support infantry"}
		{"stormtroopers4(jap)" "Elite CQB infantry"}
        {"stormtroopers(rus)" "Red Guards"}
		{"stormtroopers1(rus)" "Elite marksmen"}
		{"stormtroopers2(rus)" "Elite AT infantry"}
		{"stormtroopers3(rus)" "Elite support infantry"}
		{"stormtroopers4(rus)" "Elite CQB infantry"}
        {"stormtroopers(usa)" "Rangers"}
		{"stormtroopers1(usa)" "Elite marksmen"}
		{"stormtroopers2(usa)" "Elite AT infantry"}
		{"stormtroopers3(usa)" "Elite support infantry"}
		{"stormtroopers4(usa)" "Elite CQB infantry"}
        {"stormtroopers(hun)" "Royal guards"}
		{"stormtroopers1(hun)" "Elite marksmen"}
		{"stormtroopers2(hun)" "Elite AT infantry"}
		{"stormtroopers3(hun)" "Elite support infantry"}
		{"stormtroopers4(hun)" "Elite CQB infantry"}
        {"stormtroopers(fra)" "French SAS"}
		{"stormtroopers1(fra)" "Elite marksmen"}
		{"stormtroopers2(fra)" "Elite AT infantry"}
		{"stormtroopers3(fra)" "Elite support infantry"}
		{"stormtroopers4(fra)" "Elite CQB infantry"}
        {"stormtroopers(fin)" "Border Jaegers"}
		{"stormtroopers1(fin)" "Elite marksmen"}
		{"stormtroopers2(fin)" "Elite AT infantry"}
		{"stormtroopers3(fin)" "Elite support infantry"}
		{"stormtroopers4(fin)" "Elite CQB infantry"}
        {"stormtroopers(ita)" "Decima MAS"}
		{"stormtroopers1(ita)" "Elite marksmen"}
		{"stormtroopers2(ita)" "Elite AT infantry"}
		{"stormtroopers3(ita)" "Elite support infantry"}
		{"stormtroopers4(ita)" "Elite CQB infantry"}
        {"stormtroopers(chn)" "Stormtroopers"}
		{"stormtroopers1(chn)" "Elite marksmen"}
		{"stormtroopers2(chn)" "Elite AT infantry"}
		{"stormtroopers3(chn)" "Elite support infantry"}
		{"stormtroopers4(chn)" "Elite CQB infantry"}
        {"stormtroopers(anz)" "SASR"}
		{"stormtroopers1(anz)" "Elite marksmen"}
		{"stormtroopers2(anz)" "Elite AT infantry"}
		{"stormtroopers3(anz)" "Elite support infantry"}
		{"stormtroopers4(anz)" "Elite CQB infantry"}
        {"storm_mech_eng" "Mechanized SAS"}
		{"storm_mech_ger" "Mechanized Panzergrenadiere"}
		{"storm_mech_jap" "Mechanized SNLF"}
		{"storm_mech_rus" "Mechanized Red Guards"}
		{"storm_mech_usa" "Mechanized Rangers"}
		{"storm_mech_hun" "Mechanized Royal Guards"}
		{"storm_mech_fra" "Mechanized French SAS"}
		{"storm_mech_fin" "Mechanized Border Jaegers"}
		{"storm_mech_ita" "Mechanized Decima MAS"}
		{"storm_mech_chn" "Mechanized Stormtroopers"}
		{"storm_mech_anz" "Mechanized SASR"}
		{"tankmans(eng)" "Tank crew"}
		{"tankmans(ger)" "Tank crew"}
		{"tankmans(jap)" "Tank crew"}
		{"tankmans(rus)" "Tank crew"}
		{"tankmans(usa)" "Tank crew"}
		{"tankmans(hun)" "Tank crew"}
		{"tankmans(fra)" "Tank crew"}
		{"tankmans(fin)" "Tank crew"}
		{"tankmans(ita)" "Tank crew"}
		{"tankmans(chn)" "Tank crew"}
		{"tankmans(anz)" "Tank crew"}

		{"hero1_eng" "Saboteur"}
		{"hero2_eng" "Black Watch"}
		{"hero3_eng" "Royal Grenadiers"}
		{"hero4_eng1" "Crusader Mk. ICS"}
		{"hero5_eng" "Royal Commandos"}
		{"hero6_eng" "Cromwell Mk. VI"}
		{"hero7_eng" "Radio Operator"}
		{"hero8_eng" "Royal Artillery"}
		{"hero9_eng" "M4A4 Tulip"}
		{"hero10_eng" "Churchill Crocodile"}
		{"hero11_eng" "Churchill AVRE"}
		{"hero12_eng" "Black Prince"}

		{"hero1_ger" "Veteran Sniper"}
		{"hero2_ger1" "German Youth"}
		{"hero3_ger" "Brandenburger"}
		{"hero4_ger1" "PzKpfw III Flamer"}
		{"hero5_ger" "Fallschirmjager"}
		{"hero6_ger" "Nebelwerfer 41"}
		{"hero7_ger" "Radio Operator"}
		{"hero8_ger1" "Das Reich!"}
		{"hero9_ger" "StuH 42"}
		{"hero10_ger" "PaK 43"}
		{"hero11_ger" "Veteran Tiger"}
		{"hero12_ger" "Royal Tiger"}

		{"hero1_jap" "AT-Riflegrenade Squad"}
		{"hero2_jap1" "Kamikaze!"}
		{"hero3_jap1" "Ke-Nu"}
		{"hero4_jap" "Homeland Fury"}
		{"hero5_jap" "Marine Paratroopers"}
	    {"hero6_jap" "Type 97 Mortar"}
	    {"hero7_jap" "Marine Tank"}
	    {"hero8_jap1" "Na-To"}
		{"hero9_jap" "Radio Operator"}
		{"hero10_jap" "Banzai!"}
		{"hero11_jap" "200mm Rocket"}
		{"hero12_jap" "Ho-Ri 1"}
		
		{"hero1_rus" "Spetsnaz"}
		{"hero2_rus" "Shock Infantry"}
		{"hero3_rus1" "T-38"}
		{"hero4_rus" "Guards Sniper"}
		{"hero5_rus" "Guards Rifle"}
		{"hero6_rus" "Charge!"}
        {"hero7_rus" "BS-3"}
		{"hero8_rus" "Radio Operator"}
		{"hero9_rus" "KV-2"}
		{"hero10_rus" "BM-8-24"}
		{"hero11_rus" "Assault Troops"}
		{"hero12_rus" "203mm B-4M"}

		{"hero1_usa" "M8 Howitzer"}
		{"hero2_usa" ".30 cal Browning A6"}
		{"hero3_usa1" "Marauders"}
		{"hero4_usa" "U.S. Marines"}
		{"hero5_usa1" "M15A1 CGMC"}
		{"hero6_usa" "Devil's Brigade"}
		{"hero7_usa" "M4A3R2 Croc"}
		{"hero8_usa" "Radio Operator"}
		{"hero9_usa" "M4A3(105)"}
		{"hero10_usa" "Veteran M4A3E8(76)W Sherman"}
		{"hero11_usa" "M1 155mm Long Tom"}
		{"hero12_usa" "Super Pershing"}

        {"hero1_hun" "Csaba 40M"}
		{"hero2_hun" "Calarasi"}
		{"hero3_hun" "PzKpfw IV Ausf.D"}
		{"hero4_hun" "Szent Laszlo Infantry"}
		{"hero5_hun" "Arrow Cross Fanatics"}
		{"hero6_hun" "SdKfz 250/9"}
		{"hero7_hun" "Skoda T25"}
		{"hero8_hun" "Rapid Corps"}
		{"hero9_hun" "Radio Operator"}		
        {"hero10_hun" "15 cm sIG 33"}
        {"hero11_hun" "Sturmpanzer I Bison"}
		{"hero12_hun" "Brummbar"}

        {"hero1_fra" "Maginot Line Defenders"}
		{"hero2_fra" "Mortier de 50mm"}
		{"hero3_fra" "Vive la France"}
		{"hero4_fra" "Dywizja Grenadierow"}	
        {"hero5_fra" "Renault DCA 37mm Shneider"}
        {"hero6_fra" "Demi Brigade"}
		{"hero7_fra" "Puissance Filloux"}
		{"hero8_fra" "Char-Bis Revolver"}
		{"hero9_fra" "Radio Operator"}
		{"hero10_fra" "AMX-13/75"}
		{"hero11_fra" "Grand Battery"}
		{"hero12_fra" "AMX-50/100"}

        {"hero1_fin" "Swedish Volunteers"}
        {"hero2_fin" "Indirect Maxim Support"}
        {"hero3_fin" "Trench Clearers"}
        {"hero4_fin" "76mm M1909"}
        {"hero5_fin" "White Death"}
        {"hero6_fin" "Captured SU-152"}
        {"hero7_fin" "Toerni Detachement"}
        {"hero8_fin" "Radio Operator"}
        {"hero9_fin" "Modified KV-1"}
        {"hero10_fin" "Captured SU-152"}
        {"hero11_fin" "Veteran 152mm M1937"}
        {"hero12_fin" "Charioteer"}

        {"hero1_ita" "Polizia Militare"}
        {"hero2_ita" "Caccia Carri"}
        {"hero3_ita" "Carro Armato L35/L.F."}
        {"hero4_ita" "45mm Brixia Modello 35"}
        {"hero5_ita" "ARMIR"}
        {"hero6_ita" "Cannone Movente"}
        {"hero7_ita" "PzKpfw III Ausf.N"}
        {"hero8_ita" "Radio Operator"}
        {"hero9_ita" "Semovente M43 da 105/25"}
        {"hero10_ita" "Semovente da 75/46"}
        {"hero11_ita" "Obice da 210/35"}
        {"hero12_ita" "Elefantita"}
       
        {"hero1_chn" "Hui Muslims"}
        {"hero2_chn" "PzKpfw I Ausf.B"}
        {"hero3_chn" "Willys AT"}
        {"hero4_chn" "Guerilla Uprising"}
        {"hero5_chn" "Korean Rebels"}
        {"hero6_chn" "SU-12"}
        {"hero7_chn" "Burma Road Soliders"}
        {"hero8_chn" "122mm M1931/37 (A-19)"}
        {"hero9_chn" "Radio Operator"}
        {"hero10_chn" "China Uprising"}
        {"hero11_chn" "Foreign Aid"}
        {"hero12_chn" "WZ-111"}

        {"hero1_anz" "Boyes .55 carrier"}
        {"hero2_anz" "Volunteer Rifles"}
        {"hero3_anz" "Native Guides"}
        {"hero4_anz" "Desert Rats"}
        {"hero5_anz" "40mm M1 Bofors L/60"}
        {"hero6_anz" "Staghound OF 6-pdr"}
        {"hero7_anz" "4.2 inch Mortar carrier"}
        {"hero8_anz" "Radio Operator"}
        {"hero9_anz" "Staghound Tulip"}
        {"hero10_anz" "Churchill Mk. VCS"}
        {"hero11_anz" "Veteran M4A4 Firefly"}
        {"hero12_anz" "Sexton"}



