		{"l6a" "L6/40 Trasporto Munizioni"}
		{"m4732" "Semovente da 47/32"}
		{"m7518" "Semovente M40 da 75/18"}
		{"m7532" "Semovente M41 da 75/32"}
		{"m7534" "Semovente M41 da 75/34"}
		{"m1139" "Carro Armato M11/39"}
		{"m1340" "Carro Armato M13/40"}
		{"m1441" "Carro Armato M14/41"}
		{"m1542" "Carro Armato M15/42"}
		{"l640" "Carro Armato L6/40"}
		{"lince" "Lancia 'Lince' Autoblinda"}
		{"as37" "Fiat/SPA Autocarro Protetto AS 37"}
		{"lancia1zm" "Lancia 1ZM"}	
		{"fiat35" "Fiat Dovunque M35"}
		{"fiataa35" "Fiat Dovunque M35 2cm L/77"}
		{"fiat611" "Autoblindata Fiat 611B"}	
		{"guzzi-sa500" "Guzzi 500"}
		{"motortri" "Benelli 500"}
		{"ac35" "Autocaretta OM35"}
		{"c50cma" "Ceirano 50 CMA 7.5cm L/27 CK"}
		{"stug3gita" "StuG III Ausf.G"}		
		{"21" "Breda Modello 31"}
		{"22" "Cannone-Mitragliera da 20/77"}
		{"Bredasafat77_stan" "Breda-Safat"}		
		{"cannone6517" "Cannone da 65/17"}
		{"cannone4732" "Cannone da 47/32"}
		{"cannone7527" "Cannone da 75/27"}
		{"cannone7532" "Cannone da 75/32"}
		{"cannone9053" "Cannone da 90/53"}
		{"obice7518" "Obice da 75/18"}
		{"obice10017" "Obice da 100/17"}
		{"obice10528" "Obice da 105/28"}
		{"obice14913" "obice da 149/13"}
		{"obice149a" "Obice da 149/35"}
		{"obice210" "Obice da 210/35"}
		{"pz4gita" "PzKpfw IV Ausf.G"}		
		{"fiat633" "Fiat 633"}
		{"m9053" "Semovente M41 da 90/53"}
		{"m41c" "Carro Commando M41"}
		{"p40" "Carro Armato P40"}
		{"m10525" "Semovente M43 da 105/25"}
		{"l335" "Carro Veloce L3/35"}
		{"l335c" "Carro Armato L35/c"}
		{"l35lf" "Carro Armato L35/L.F."}
		{"ab40" "Fiat-Ansaldo Autoblindo AB40"}
		{"ab41" "Fiat-Ansaldo Autoblindo AB41"}
		{"ab43" "Fiat-Ansaldo Autoblindo AB43"}
		{"as421" "Camionette AS.42 Sahariana"}
		{"as422" "Camionette AS.42 20/ Sahariana"}
		{"as423" "Camionette AS.42 47/ Sahariana"}
		{"665nm" "Fiat 665NM Scudato"}
		{"fiat35_inf" "Fiat Dovunque M35"}
		{"fiat35_art" "Fiat Dovunque M35"}
		{"fiat35_eng" "Fiat Dovunque M35"}
		{"how_a(ita)" "sFH 18"}
		{"how_b(ita)" "le. FH 18 M"}
		{"obice14940" "Obice da 149/40"}		
		{"fiat508cm" "Fiat 508 CM"}
		{"breda_37stan" "Fucile Mitragliatore Breda modello 37"}
		{"brixia45" "45mm Brixia Modello 35"}
		{"mortaio81" "Mortaio da 81 Mod.35"}
		{"np_sdkfz251_ita" "Sd.Kfz. 251/1"}
		{"pz3nita" "PzKpfw III Ausf.N"}
		{"20mmScotti" "Cannone-Mitragliera da 20/77"}
		{"breda_safat88_stan" "Heavy MG"}
		{"sgrw42_ita" "Mortaio da 81/14 Modello 35"}
		{"pz4gita" "PzKpfw IV Ausf.F2"}
		{"pz4hita" "PzKpfw IV Ausf.H"}
		{"pz38tita" "PzKpfw 38(t) Ausf.F"}
		{"kv1b" "PzKpfw KV-1B 756(r)"}
		{"3ro" "Lancia 3 Cannone 90mm"}
		{"m7546" "Semovente da 75/46"}
                {"autocannone10017" "Autocannone 100/17"}
                {"c50cma" "Ceirano 7.5"}
		


		