                {"arl" "Air rocket"}
		{"bullet20 airplane" "AP 20mm FlaK rounds"}
		{"bullet20 zenite" "AP 20mm Zenite"}
		{"bullet25 zenite" "AP 25mm FlaK rounds"}
		{"bullet37 ap" "AP 37mm"}
		{"bullet37 apcr" "APCR 37mm"}
		{"bullet37 fg" "HE 37mm"}
		{"bullet37 zenite" "AP 37mm FlaK rounds"}
		{"bullet40 ap" "AP 40mm"}
		{"bullet40 apcr" "APCR 40mm"}
		{"bullet40 fg" "HE 40mm"}
		{"bullet40 zenite" "AP 40mm FlaK rounds"}
		{"bullet45 ap" "AP 45mm"}
		{"bullet45 apcr" "APCR 45mm"}
		{"bullet45 fg" "HE 45mm"}
		{"bullet47 ap" "AP 47mm"}
		{"bullet47 apcr" "APCR 47mm"}
		{"bullet47 fg" "HE 47mm"}
		{"bullet50 ap" "AP 50mm"}
		{"bullet50 apcr" "APCR 50mm"}
		{"bullet50 fg" "HE 50mm"}
		{"bullet57 ap" "AP 57mm"}
		{"bullet57 apcr" "APCR 57mm"}
		{"bullet57 fg" "HE 57mm"}
		{"bullet75 ap" "AP 75mm"}
		{"bullet75 apcr" "APCR 75mm"}
		{"bullet75 fg" "HE 75mm"}
		{"bullet75 heat" "HEAT 75mm"}
		{"bullet76 ap" "AP 76mm"}
		{"bullet76hvap ap" "AP 76mm"}
		{"bullet76 apcr" "APCR 76mm"}
		{"bullet76hvap apcr" "HVAP 76mm"}
		{"bullet76 fg" "HE 76mm"}
		{"bullet76hvap fg" "HE 76mm"}
		{"bullet77 ap" "AP 77mm"}
		{"bullet77 apcr" "APCR 77mm"}
		{"bullet77 fg" "HE 77mm"}
		{"bullet85 ap" "AP 85mm"}
		{"bullet85 apcr" "APCR 85mm"}
		{"bullet85 fg" "HE 85mm"}
		{"bullet89 ap" "AP 87.6mm"}
		{"bullet89 apcr" "APCR 87.6mm"}
		{"bullet89 fg" "HE 87.6mm"}
		{"bullet88 ap" "AP 88mm"}
		{"bullet88 apcr" "APCR 88mm"}
		{"bullet88 fg" "HE 88mm"}
		{"bullet90 ap" "AP 90mm"}
		{"bullet90 apcr" "APCR 90mm"}
		{"bullet90 fg" "HE 90mm"}
		{"bullet93 ap" "AP 93mm"}
		{"bullet93 apcr" "APCR 93mm"}
		{"bullet93 fg" "HE 93mm"}
		{"bullet95 ap" "AP 95mm"}
		{"bullet95 apcr" "APCR 95mm"}
		{"bullet95 fg" "HE 95mm"}
		{"bullet100 ap" "AP 100mm"}
		{"bullet100 apcr" "APCR 100mm"}
		{"bullet100 fg" "HE 100mm"}
		{"bullet105 ap" "AP 105mm"}
		{"bullet105 apcr" "APCR 105mm"}
		{"bullet105 fg" "HE 105mm"}
		{"bullet105 sm" "SMOKE 105mm"}
		{"bullet114 fg" "HE 114mm"}
		{"bullet120 ap" "AP 120mm"}
		{"bullet120 apcr" "APCR 120mm"}
		{"bullet120 fg" "HE 120mm"}
		{"bullet122 ap" "AP 122mm"}
		{"bullet122 apcr" "APCR 122mm"}
		{"bullet122 fg" "HE 122mm"}
		{"bullet122 sm" "SMOKE 122mm"}
		{"bullet128 ap" "AP 128mm"}
		{"bullet128 apcr" "APCR 128mm"}
		{"bullet128 fg" "HE 128mm"}
		{"bullet150 ap" "AP 150mm"}
		{"bullet150 fg" "HE 150mm"}
		{"bullet150 sm" "SMOKE 150mm"}
		{"bullet152 ap" "AP 152mm"}
		{"bullet152 fg" "HE 152mm"}
		{"bullet152 sm" "SMOKE 152mm"}
		{"bullet155 fg" "HE 155mm"}
		{"bullet155 sm" "SMOKE 155mm"}
		{"bullet203" "HE 203mm"}
		{"bullet290" "HE 290mm"}
		{"bullet305" "305mm round"}
		{"20cm_rocket" "200mm Type 4 rocket"}
		{"30cm_rocket" "300mm Type 4 rocket"}
		{"air_bomb" "Bomb"}
		{"air_bomb_il2" "Bomb"}
		{"air_bomb stuff" "Bomb"}
		{"bazooka" "AT Bazooka rocket"}
		{"bm8" "82mm BM-8 rocket"}
		{"calliope" "114mm M8 rocket"}
		{"flaergun ammo" "Artillery signal ammo"}
		{"goliath" "Demolition charge"}
		{"hmgun" "HMG ammo"}
		{"katusha" "132mm BM-13 rocket"}
		{"lm_ammo" "76mm RP-3 rocket"}
		{"m18recoilless" "AT M18 recoilless projectile"}
		{"mgun" "MG ammo"}
		{"mortar fg" "Mortar shell"}
		{"mortar150 fg" "Heavy mortar shell"}
		{"mortar sm" "Smoke Mortar shell"}
		{"nebel41" "150mm Nebelwerfer 41 rocket"}
		{"nebel42" "210mm Nebelwerfer 42 rocket"}
		{"panzerfaust" "AT Panzerfaust projectile"}
		{"panzershreck" "AT Panzerschreck rocket"}
		{"panzerwerfer42" "150mm Nebelwerfer rocket"}
		{"piatrocket" "AT PIAT projectile"}
		{"ptr" "AT-Rifle rounds"}
		{"rifle" "Rifle ammo"}
		{"rifle_grenade" "Rifle grenade"}
		{"rifle_grenade_at" "AT-Rifle grenade"}
		{"searchlight" ""}
		{"shotgun" "Shotgun ammo"}
		{"smg" "SMG ammo"}
		{"sturmtiger" "380mm Sturmtiger rocket"}
		{"tulip" "76mm Tulip rocket"}
		{"torpedo" "Torpedo"}
		{"type_4" "AT Type 4 rocket"}
                {"m31" "M31 rounds"}
                {"mortar50.fguk" "Mortar shell"}
                {"bullet25.ap" "Bullets"}
                {"bullet25.fg" "Bullets"}
                {"smoke" "Smoke rounds"}
                {"smokecaller" "Smoke rounds"}
		;------- VAN
