                {"ap_miners(eng)" "Combat engineers (infantry)"}
		{"ap_miners(ger)" "Combat engineers (infantry)"}
		{"ap_miners(jap)" "Combat engineers (infantry)"}
		{"ap_miners(rus)" "Combat engineers (infantry)"}
		{"ap_miners(usa)" "Combat engineers (infantry)"}
		{"ap_miners(hun)" "Combat engineers (infantry)"}
		{"ap_miners(fra)" "Combat engineers (infantry)"}
		{"ap_miners(fin)" "Combat engineers (infantry)"}
		{"ap_miners(ita)" "Combat engineers (infantry)"}
		{"ap_miners(chn)" "Combat engineers (infantry)"}		
                {"at_miners(eng)" "Combat engineers (vehicle)"}
		{"at_miners(ger)" "Combat engineers (vehicle)"}
		{"at_miners(jap)" "Combat engineers (vehicle)"}
		{"at_miners(rus)" "Combat engineers (vehicle)"}
		{"at_miners(usa)" "Combat engineers (vehicle)"}
		{"at_miners(hun)" "Combat engineers (vehicle)"}
		{"at_miners(fra)" "Combat engineers (vehicle)"}
		{"at_miners(fin)" "Combat engineers (vehicle)"}
		{"at_miners(ita)" "Combat engineers (vehicle)"}
		{"at_miners(chn)" "Combat engineers (vehicle)"}
		{"at_rifles(eng)" "AT-Rifle infantry"}
		{"at_rifles(ger)" "AT-Rifle infantry"}
		{"at_rifles(jap)" "AT-Rifle infantry"}
		{"at_rifles(rus)" "AT-Rifle infantry"}
		{"at_rifles(hun)" "AT-Rifle infantry"}
		{"at_rifles(fra)" "AT-Rifle infantry"}
		{"at_rifles(fin)" "AT-Rifle infantry"}
		{"at_rifles(ita)" "AT-Rifle infantry"}
		{"at_rifles(chn)" "AT-Rifle infantry"}
		{"bazookers(eng)" "AT infantry"}
		{"bazookers(ger)" "AT infantry"}
		{"bazookers(jap)" "AT infantry"}
		{"bazookers(rus)" "AT infantry"}
		{"bazookers(usa)" "AT infantry"}
		{"bazookers(hun)" "AT infantry"}
		{"bazookers(fra)" "AT infantry"}
		{"bazookers(fin)" "AT infantry"}
		{"bazookers(ita)" "AT infantry"}
		{"bazookers(chn)" "AT infantry"}
		{"elites(eng)" "Commandos"}
		{"elites(ger)" "Paratroopers"}
		{"elites(jap)" "Paratroopers"}
		{"elites(rus)" "Marines"}
		{"elites(usa)" "Airborne"}
		{"elites(hun)" "Paratroopers"}
		{"elites(fra)" "Foreign Legion"}
		{"elites(fin)" "Kaukopartio"}
		{"elites(ita)" "Paracadutisti"}
		{"elites(chn)" "Foreign-trained infantry"}
		{"flamers(eng)" "Flamethrower infantry"}
		{"flamers(ger)" "Flamethrower infantry"}
		{"flamers(jap)" "Flamethrower infantry"}
		{"flamers(rus)" "Flamethrower infantry"}
		{"flamers(usa)" "Flamethrower infantry"}
		{"flamers(hun)" "Flamethrower infantry"}
		{"flamers(fra)" "Flamethrower infantry"}
		{"flamers(fin)" "Flamethrower infantry"}
		{"flamers(ita)" "Flamethrower infantry"}
		{"flamers(chn)" "Flamethrower infantry"}
		{"home_guards(eng)" "Militia"}
		{"home_guards(ger)" "Volkssturm"}
		{"home_guards(jap)" "Recruits"}
		{"home_guards(rus)" "Partisan"}
		{"home_guards(usa)" "Conscripts"}
		{"home_guards(hun)" "Conscripts"}
		{"home_guards(fra)" "Resistance"}
		{"home_guards(fin)" "Reservists"}
		{"home_guards(ita)" "Milizia"}
		{"home_guards(chn)" "Peasants"}
		{"kamikazes(jap)" "Kamikaze"}
		{"mgs2(eng)" "Machine gunner"}
		{"mgs2(ger)" "Machine gunner"}
		{"mgs2(jap)" "Machine gunner"}
		{"mgs2(rus)" "Machine gunner"}
		{"mgs2(usa)" "Machine gunner"}
		{"mgs2(hun)" "Machine gunner"}
		{"mgs2(fra)" "Machine gunner"}
		{"mgs2(fin)" "Machine gunner"}
		{"mgs2(ita)" "Machine gunner"}
		{"mgs2(chn)" "Machine gunner"}
		{"officers(eng)" "Officer"}
		{"officers(ger)" "Officer"}
		{"officers(jap)" "Officer"}
		{"officers(rus)" "Officer"}
		{"officers(usa)" "Officer"}
		{"officers(hun)" "Officer"}
		{"officers(fra)" "Officer"}
		{"officers(fin)" "Officer"}
		{"officers(ita)" "Officer"}
		{"officers(chn)" "Officer"}
		{"riflemans(eng)" "Regular infantry"}
		{"riflemans(ger)" "Regular infantry"}
		{"riflemans(jap)" "Regular infantry"}
		{"riflemans(rus)" "Regular infantry"}
		{"riflemans(usa)" "Regular infantry"}
		{"riflemans(hun)" "Regular infantry"}
		{"riflemans(fra)" "Regular infantry"}
		{"riflemans(fin)" "Regular infantry"}
		{"riflemans(ita)" "Regular infantry"}
		{"riflemans(chn)" "Regular infantry"}
		{"riflemans2(eng)" "Rifleman"}
		{"riflemans2(ger)" "Rifleman"}
		{"riflemans2(jap)" "Rifleman"}
		{"riflemans2(rus)" "Rifleman"}
		{"riflemans2(usa)" "Rifleman"}
		{"riflemans2(hun)" "Rifleman"}
		{"riflemans2(fra)" "Rifleman"}
		{"riflemans2(fin)" "Rifleman"}
		{"riflemans2(ita)" "Rifleman"}
		{"riflemans2(chn)" "Rifleman"}
		{"sappers(eng)" "Mine disposal experts"}
		{"sappers(ger)" "Mine disposal experts"}
		{"sappers(jap)" "Mine disposal experts"}
		{"sappers(rus)" "Mine disposal experts"}
		{"sappers(usa)" "Mine disposal experts"}
		{"sappers(hun)" "Mine disposal experts"}
		{"sappers(fra)" "Mine disposal experts"}
		{"sappers(fin)" "Mine disposal experts"}
		{"sappers(ita)" "Mine disposal experts"}
		{"sappers(chn)" "Mine disposal experts"}
		{"smgs(eng)" "Assault infantry"}
		{"smgs(ger)" "Assault infantry"}
		{"smgs(jap)" "Assault infantry"}
		{"smgs(rus)" "Assault infantry"}
		{"smgs(usa)" "Assault infantry"}
		{"smgs(hun)" "Assault infantry"}
		{"smgs(fra)" "Assault infantry"}
		{"smgs(fin)" "Assault infantry"}
		{"smgs(ita)" "Assault infantry"}
		{"smgs(chn)" "Assault infantry"}
		{"smgs2(eng)" "SMG"}
		{"smgs2(ger)" "SMG"}
		{"smgs2(jap)" "SMG"}
		{"smgs2(rus)" "SMG"}
		{"smgs2(usa)" "SMG"}
		{"smgs2(hun)" "SMG"}
		{"smgs2(fra)" "SMG"}
		{"smgs2(fin)" "SMG"}
		{"smgs2(ita)" "SMG"}
		{"smgs2(chn)" "SMG"}
                {"smgs3(eng)" "Demolition specialist"}
		{"smgs3(ger)" "Demolition specialist"}
		{"smgs3(jap)" "Demolition specialist"}
		{"smgs3(rus)" "Demolition specialist"}
		{"smgs3(usa)" "Demolition specialist"}
		{"smgs3(hun)" "Demolition specialist"}
		{"smgs3(fra)" "Demolition specialist"}
		{"smgs3(fin)" "Demolition specialist"}
		{"smgs3(ita)" "Demolition specialist"}
		{"smgs3(chn)" "Demolition specialist"}
                {"elites2(eng)" "Veteran rifleman"}
		{"elites2(ger)" "Veteran rifleman"}
		{"elites2(jap)" "Veteran rifleman"}
		{"elites2(rus)" "Veteran rifleman"}
		{"elites2(usa)" "Veteran rifleman"}
		{"elites2(hun)" "Veteran rifleman"}
		{"elites2(fra)" "Veteran rifleman"}
		{"elites2(fin)" "Veteran rifleman"}
		{"elites2(ita)" "Veteran rifleman"}
		{"elites2(chn)" "Veteran rifleman"}
                {"snipers(eng)" "Sniper"}
		{"snipers(ger)" "Sniper"}
		{"snipers(jap)" "Sniper"}
		{"snipers(rus)" "Sniper"}
		{"snipers(usa)" "Sniper"}
		{"snipers(hun)" "Sniper"}
		{"snipers(fra)" "Sniper"}
		{"snipers(fin)" "Sniper"}
		{"snipers(ita)" "Sniper"}
		{"snipers(chn)" "Sniper"}
		{"snipers_d(eng)" "Sniper"}
		{"snipers_d(ger)" "Sniper"}
		{"snipers_d(jap)" "Sniper"}
		{"snipers_d(rus)" "Sniper"}
		{"snipers_d(usa)" "Sniper"}
		{"snipers_d(hun)" "Sniper"}
		{"snipers_d(fra)" "Sniper"}
		{"snipers_d(fin)" "Sniper"}
		{"snipers_d(ita)" "Sniper"}
		{"snipers_d(chn)" "Sniper"}
		{"shotguns(usa)" "Shotgunners"}
		{"stormtroopers(eng)" "SAS"}
		{"stormtroopers1(eng)" "Elite marksmen"}
		{"stormtroopers2(eng)" "Elite AT infantry"}
		{"stormtroopers3(eng)" "Elite support infantry"}
                {"stormtroopers4(eng)" "Elite CQB infantry"}
		{"stormtroopers(ger)" "Panzergrenadiere"}
		{"stormtroopers1(ger)" "Elite marksmen"}
		{"stormtroopers2(ger)" "Elite AT infantry"}
		{"stormtroopers3(ger)" "Elite support infantry"}
		{"stormtroopers4(ger)" "Elite CQB infantry"}
                {"stormtroopers(jap)" "SNLF"}
		{"stormtroopers1(jap)" "Elite marksmen"}
		{"stormtroopers2(jap)" "Elite AT infantry"}
		{"stormtroopers3(jap)" "Elite support infantry"}
		{"stormtroopers4(jap)" "Elite CQB infantry"}
                {"stormtroopers(rus)" "Red Guards"}
		{"stormtroopers1(rus)" "Elite marksmen"}
		{"stormtroopers2(rus)" "Elite AT infantry"}
		{"stormtroopers3(rus)" "Elite support infantry"}
		{"stormtroopers4(rus)" "Elite CQB infantry"}
                {"stormtroopers(usa)" "Rangers"}
		{"stormtroopers1(usa)" "Elite marksmen"}
		{"stormtroopers2(usa)" "Elite AT infantry"}
		{"stormtroopers3(usa)" "Elite support infantry"}
		{"stormtroopers4(usa)" "Elite CQB infantry"}
                {"stormtroopers(hun)" "Royal guards"}
		{"stormtroopers1(hun)" "Elite marksmen"}
		{"stormtroopers2(hun)" "Elite AT infantry"}
		{"stormtroopers3(hun)" "Elite support infantry"}
		{"stormtroopers4(hun)" "Elite CQB infantry"}
                {"stormtroopers(fra)" "French SAS"}
		{"stormtroopers1(fra)" "Elite marksmen"}
		{"stormtroopers2(fra)" "Elite AT infantry"}
		{"stormtroopers3(fra)" "Elite support infantry"}
		{"stormtroopers4(fra)" "Elite CQB infantry"}
                {"stormtroopers(fin)" "Border Jaegers"}
		{"stormtroopers1(fin)" "Elite marksmen"}
		{"stormtroopers2(fin)" "Elite AT infantry"}
		{"stormtroopers3(fin)" "Elite support infantry"}
		{"stormtroopers4(fin)" "Elite CQB infantry"}
                {"stormtroopers(ita)" "Decima MAS"}
		{"stormtroopers1(ita)" "Elite marksmen"}
		{"stormtroopers2(ita)" "Elite AT infantry"}
		{"stormtroopers3(ita)" "Elite support infantry"}
		{"stormtroopers4(ita)" "Elite CQB infantry"}
                {"stormtroopers(chn)" "Stormtroopers"}
		{"stormtroopers1(chn)" "Elite marksmen"}
		{"stormtroopers2(chn)" "Elite AT infantry"}
		{"stormtroopers3(chn)" "Elite support infantry"}
		{"stormtroopers4(chn)" "Elite CQB infantry"}
                {"storm_mech_eng" "Mechanized SAS"}
		{"storm_mech_ger" "Mechanized Panzergrenadiere"}
		{"storm_mech_jap" "Mechanized SNLF"}
		{"storm_mech_rus" "Mechanized Red Guards"}
		{"storm_mech_usa" "Mechanized Rangers"}
		{"storm_mech_hun" "Mechanized Royal Guards"}
		{"storm_mech_fra" "Mechanized French SAS"}
		{"storm_mech_fin" "Mechanized Border Jaegers"}
		{"storm_mech_ita" "Mechanized Decima MAS"}
		{"storm_mech_chn" "Mechanized Stormtroopers"}
		{"tankmans(eng)" "Tank crew"}
		{"tankmans(ger)" "Tank crew"}
		{"tankmans(jap)" "Tank crew"}
		{"tankmans(rus)" "Tank crew"}
		{"tankmans(usa)" "Tank crew"}
		{"tankmans(hun)" "Tank crew"}
		{"tankmans(fra)" "Tank crew"}
		{"tankmans(fin)" "Tank crew"}
		{"tankmans(ita)" "Tank crew"}
		{"tankmans(chn)" "Tank crew"}
		{"hero1_eng" "Saboteur"}
		{"hero2_eng1" "Royal Grenadiers"}
		{"hero3_eng" "ANZAC"}
		{"hero4_eng" "Royal Commandos"}
		{"hero5_eng" "Radio Operator"}
		{"hero6_eng" "Churchill Crocodile"}
		{"hero7_eng" "Royal Artillery"}
		{"hero8_eng" "Churchill AVRE"}
		{"hero9_eng" "Black Prince"}
		{"heronew1_eng" "Black Watch"}
		{"heronew2_eng" "Cromwell Mk. VI"}
		{"heronew3_eng" "M4A4 Tulip"}
		{"heronew4_eng" "Challenger (A30)"}
		{"heronew5_eng" "Staghound Tulip"}
		{"heronew6_eng" "LDGR"}
		{"hero1_ger" "Veteran Sniper"}
		{"hero2_ger" "Brandenburger"}
		{"hero3_ger1" "Volksgrenadier"}
		{"hero4_ger" "Fallschirmjager"}
		{"hero5_ger" "Radio Operator"}
		{"hero6_ger" "StuH 42"}
		{"hero7_ger" "Nebelwerfer 41"}
		{"hero8_ger" "Veteran Tiger"}
		{"hero9_ger" "Sturmtiger"}
		{"heronew1_ger1" "German Youth"}
		{"heronew2_ger1" "Sd.Kfz.8 8.8cm Flak"}
		{"heronew3_ger" "PaK 43"}
		{"heronew4_ger1" "PzKpfw III Flamer"}
		{"heronew5_ger" "Faux M10 Wolverine"}
		{"heronew6_ger" "Das Reich!"}
		{"hero1_jap" "AT-Riflegrenade Squad"}
		{"hero2_jap" "Kamikaze!"}
		{"hero3_jap" "Homeland Fury"}
		{"hero4_jap" "Marine Paratroopers"}
		{"hero5_jap" "Radio Operator"}
		{"hero6_jap" "Banzai!"}
		{"hero7_jap" "200mm Rocket"}
		{"hero8_jap" "Marine Tank"}
		{"hero9_jap" "Ho-Ri 1"}
		{"heronew1_jap1" "Takasago Volunteers"}
		{"heronew2_jap1" "Na-To"}
		{"heronew3_jap" "Type 97 Mortar"}
		{"heronew4_jap" "Type 89 Chi-Ho"}
		{"heronew5_jap" "Knee Mortarers"}
		{"heronew6_jap" "Divine Wind"}
		{"hero1_rus" "Spetsnaz"}
		{"hero2_rus" "Guards Rifle"}
		{"hero3_rus" "Guards Sniper"}
		{"hero4_rus" "Black Coats"}
		{"hero5_rus" "Charge!"}
		{"hero6_rus" "Radio Operator"}
		{"hero7_rus1" "Gaz-AAA 4Maxim"}
		{"hero8_rus" "KV-2"}
		{"hero9_rus" "203mm B-4M"}
		{"heronew1_rus" "Shock Infantry"}
		{"heronew2_rus" "BS-3"}
		{"heronew5_rus" "Frontline Artillery"}
		{"heronew6_rus" "BM-8-24"}
		{"hero1_usa" "M8 Howitzer"}
		{"hero2_usa1" "101st Airborne"}
		{"hero3_usa1" "U.S. Marines"}
		{"hero4_usa" "M4A3R2 Croc"}
		{"hero5_usa" "Radio Operator"}
		{"hero6_usa" "M4A3(105)"}
		{"hero7_usa1" "Elite M4A3E8(76)W Sherman"}
		{"hero8_usa" "M4A3E2(76)W Jumbo"}
		{"hero9_usa" "Super Pershing"}
		{"heronew1_usa" ".30 cal Browning A6"}
		{"heronew2_usa1" "Marauders"}
		{"heronew3_usa" "Devil's Brigade"}
		{"heronew4_usa" "M3 Scout"}
		{"heronew5_usa" "M15A1 CGMC"}
		{"heronew6_usa" "M1 155mm Long Tom"}
		{"hero1_hun" "76mm Divisional Gun"}
		{"hero8_hun" "SdKfz 250/9"}
		{"hero2_hun" "TACAM T-60"}
		{"hero4_hun" "Rapid Corps"}
		{"hero5_hun" "Radio Operator"}		
                {"hero9_hun" "Tas 44M TD"}
		{"hero9_hun_new" "Brummbar"}
                {"heronew1_hun" "Csaba 40M"}
		{"heronew1_2_hun" "Calarasi"}
		{"heronew2_hun" "Szent Laszlo Infantry"}
		{"heronew4_hun" "Arrow Cross Fanatics"}
                {"heronew5_hun" "PzKpfw IV Ausf.D"}
                {"heronew6_hun" "Nashorn"}
                {"heronew7_hun" "Skoda T25"}
                {"heronew8_hun" "Sturmpanzer I Bison"}
                {"hero1_fra" "Dywizja Grenadierow"}
		{"hero2_fra" "Mortier de 50mm"}
		{"hero3_fra" "Vive la France"}
		{"hero4_fra" "Citroen Mortar Truck"}
		{"hero5_fra" "Demi Brigade"}
		{"hero6_fra" "Char-Bis Revolver"}	
		{"hero7_fra" "Radio Operator"}	
                {"hero8_fra" "Grand Battery"}
                {"hero9_fra" "AMX-50/100"}
		{"heronew1_fra" "Resistance Sniper"}
		{"heronew2_fra" "Renault DCA 37mm Shneider"}
		{"heronew3_fra" "AMX-13/75"}
		{"heronew4_fra" "Laffly S15 TOE"}
		{"heronew5_fra" "Maginot Line Defenders"}
		{"heronew6_fra" "Puissance Filloux"}
                {"hero1_fin" "Swedish Volunteers"}
                {"hero2_fin" "Trench Cleaners"}
                {"hero3_fin" "White Death"}
                {"hero4_fin" "T-34/76 Sotka"}
                {"hero5_fin" "BT-42"}
                {"hero6_fin" "Radio Operator"}
                {"hero7_fin" "Field-Modified KV-1"}
                {"hero8_fin" "Veteran 152mm M1937"}
                {"hero9_fin" "Captured SU-152"}
                {"heronew1_fin" "Indirect Maxim Support"}
                {"heronew2_fin" "76mm M1909"}
                {"heronew3_fin" "Toerni Detachement"}
                {"heronew4_fin" "PzKpfw IV Ausf.J"}
                {"heronew5_fin" "Nebelwerfer 42"}
                {"heronew6_fin" "Vickers 47mm"}
                {"hero1_ita" "Polizia Militare"}
                {"hero2_ita" "Afrika Korps"}
                {"hero3_ita" "Carro Armato L35/L.F."}
                {"hero4_ita" "45mm Brixia Modello 35"}
                {"hero5_ita" "Italian Blitzkreig"}
                {"hero6_ita" "Elefantita"}
                {"hero8_ita" "PzKpfw III Ausf.N"}
                {"hero9_ita" "Obice da 210/35"}
                {"heronew1_ita" "Caccia Carri"}
                {"heronew2_ita" "ARMIR"}
                {"heronew3_ita" "Radio Operator"}
                {"heronew4_ita" "Semovente M43 da 105/25"}
                {"hero1_chn" "Hui Muslims"}
                {"hero2_chn" "Willys AT"}
                {"hero3_chn" "Guerilla Uprising"}
                {"hero4_chn" "SU-12"}
                {"hero5_chn" "Radio Operator"}
                {"hero6_chn" "Korean Rebels"}
                {"hero8_chn" "China Uprising"}
                {"hero9_chn" "T-34-1"}
                {"heronew1_chn" "PzKpfw I Ausf.B"}
                {"heronew2_chn" "Bruma Road Soliders"}
                {"heronew3_chn" "122mm M1931/37 (A-19)"}
                {"heronew4_chn" "Foreign Aid"}



