                {"breda_38" "Breda 38"}
                {"breda_38_x2" "Breda 38"}
                {"gebauer" "GKM 1940"}
                {"madsen" "Madsen LMG"}
                {"mg13" "MG 13"}
                {"zb_30lmg" "ZB vz.30"}
                {"frommer_37m" "FEG 37M"}
                {"feg_35m" "FEG 35M"}
                {"feg_43m" "FEG 43M"}
                {"mannlicher_m1895" "Mannlicher M1895"}
                {"mannlicher_m1895c" "Mannlicher M1895 C"}
                {"zh-29" "ZH-29"}
                {"zb24_s" "vz.24 Sniper"}
                {"danuvia_39m" "Danuvia 39M"}
                {"danuvia_43m" "Danuvia 43M"}
                {"solothurn" "Solothurn ATR"}
                {"danuvia_39m" "Danuvia 39M"}
                {"danuvia_43m" "Danuvia 43M"}
                {"orita" "Orita M1941"}
                {"ppd" "PPD-40"}