		{"20mm_m35" "2cm Breda M35 L/65"}
		{"20mm_Scotti" "2cm Scotti L/77"}
		{"20mm_solothurn" "2cm Solothurn S-18/1000"}
		{"37mm_l40" "3.7cm Vickers-Terni L/40"}
		{"47mm_m47_40" "4.7cm Ansaldo L/40"}
		{"47mm_m47_32" "4.7cm Ansaldo L/32"}
		{"65mm_m65_17" "6.5cm L/13"}
		{"75mm_m75_18" "7.5cm Ansaldo L/18"}
		{"75mm_m75_27" "7.5cm Ansaldo L/27"}
		{"75mm_m75_27ck" "7.5cm L/27 C.K."}
		{"75mm_m75_32" "7.5cm Ansaldo L/32"}
		{"75mm_m75_34" "7.5cm Ansaldo L/34"}
		{"75mm_m75_46" "7.5cm Ansaldo L/46"}
		{"90mm_m90_53" "9cm Ansaldo L/53"}
		{"105mm_m105_25" "10.5cm Ansaldo L/25"}
		{"105mm_m105_28" "10.5cm Schneider L/28"}
		{"149mm_obice" "14.9cm Obice L/35"}
		{"brixia45" "Brixia 45mm Mortar"}
		{"flame_thrower_tank_ita" "L6 Lancia fiamme"}
		{"solothurn" "Solothurn S/100"}
		{"Bodeo_m1889" "Bodeo Mod.1889"}
		{"mab_38a" "Beretta Model 38"}
		{"mab_42" "Beretta Model 42"}
		{"beretta_m1934" "Beretta M 1934"}
		{"carcano_m91_scoped" "Carcano Mod.1891 (di precisione)"}
		{"carcano_m91" "Carcano Modello 1891"}
		{"carcano_m91-38" "Carcano Modello 1891/38"}
		{"Fnab_m1943" "FNAB Mod.1943"}
		{"breda_30" "Breda modello 30"}
		{"breda_37" "Breda modello 37"}
		{"breda_37_x2" "2 x Breda modello 37"}
		{"breda_38" "Breda modello 38"}
		{"breda_38_x2" "2 x Breda modello 38"}
		{"breda_m5c" "6.5mm Breda Mod 5C"}
		{"breda_safat88" "7.7mm Breda-Safat"}
		{"fiat_65" "8mm Revelli Modello 35"}
		{"fiat_65_x2" "2 x 8mm Revelli Modello 35"}
		{"fiat_14" "6.5mm Revelli Modello 14"}
		{"hotchkiss_132" "13.2mm Modello 31"}
		{"glisenti" "Glisenti M1910"}
		{"Berettam1918" "Beretta M1918"}
		{"vetterlim70" "Vetterli M70/87/15"}
		{"scottix" "Scotti Model X"}
		{"lanciafiamme" "Flamethrower Mod. 40"}
		{"m149_40" "14.9cm Obice L/40"}
		{"210mm_gun" "21cm Obice L/22"}
