		{"mp"		
			{"ita"
				{"at_miner" "<c(c3baae)>combat engineer (vehicle)"}
				{"ap_miner" "<c(c3baae)>combat engineer (infantry)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>paracadutisti"}
				{"elite2" "<c(c3baae)>paracadutisti"}
				{"elite3" "<c(c3baae)>paracadutisti"}
                                {"elite_at" "<c(c3baae)>paracadutisti"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>milizia"}
				{"home_guard2" "<c(c3baae)>milizia"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"mgun2" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"smg3" "<c(c3baae)>demolition specialist"}
                                {"sniper" "<c(c3baae)>sniper"}
				{"sturmovik" "<c(c3baae)>decima mas"}
				{"sturmovik2" "<c(c3baae)>decima mas"}
				{"sturmovik3" "<c(c3baae)>decima mas"}
				{"sturmovik4" "<c(c3baae)>decima mas"}
				{"sturmovik4b" "<c(c3baae)>decima mas"}
				{"sturmovik5" "<c(c3baae)>decima mas"}
				{"sturmovik5b" "<c(c3baae)>decima mas"}
				{"sturmovik6" "<c(c3baae)>decima mas"}
				{"sturmovik6b" "<c(c3baae)>decima mas"}
				{"sturmovik7" "<c(c3baae)>decima mas"}
                                {"sturmovik7b" "<c(c3baae)>decima mas"}
                                {"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
		}