		{"bammo" "bammo"}
		{"sdkfz222a" "SdKfz 222"}	
		{"gaz-mm" "Gaz-MM"}
		{"gaz-mm_inf" "Gaz-MM"}
		{"gaz-mm_art" "Gaz-MM"}
		{"gaz-mm_eng" "Gaz-MM"}
		{"ft17_chn" "FT-17"}
		{"l335_chn" "L3/33"}
		{"t-26_chn_1931" "T-26 mod. 1931"}
		{"t-26_chn_1933" "T-26 mod. 1933"}
		{"vickers_chn" "Vickers 6-ton"}
		{"a19" "A-19"}
		{"sfh18_chn" "15 cm sFH 18"}
		{"browning_1917_mgun" "Browning 1917"}
		{"maxim_chn" "PM M1910"}
		{"pak35_chn" "PaK 35"}
		{"76mm_m1909" "76mm M1909"}
		{"how_a(chn)" "sFH 18"}
		{"how_b(chn)" "le. FH 18 M"}
		{"gazaaa4m" "Gaz-AAA 4Maxim"}
		{"ba-6" "BA-6"}
		{"bt5_chn" "BT-5"} 
		{"pz1a" "PzKpfw I Ausf. A"}
		{"np_su12" "SU-12"}
		{"bm37_chn" "BM-37 mortar"}
		{"m3_chn"  "M3A1"}
		{"m3cannon_chn"  "M3 AT gun"}
		{"m1mortar_chn"  "M1 mortar"}
		{"m3a1scout_chn" "M3A1 Scout Car"}
		{"m2a4_chn" "M2A4"}
		{"m3a1_chn"  "M3A1"}
		{"m5a1_chn"  "M5A1"}
		{"m24_chn" "M24 Chaffee"}
		{"m4a4_chn" "M4 Sherman"}
		{"m18_chn" "M18 Hellcat"}
		{"chevrolet" "Chevrolet G7107"}
		{"chevrolet_art" "Chevrolet G7107"}
		{"chevrolet_eng" "Chevrolet G7107"}
		{"gun_carrier_chn" "Mortar carrier"}
		{"willysmb_chn" "Willys MB"}
		{"willysat_chn" "Willys AT"}
		{"m17_stan" "Heavy MG"}
		{"20mmscotti_chn" "Cannone-Mitragliera da 20/77"}
		{"cannone4732_chn" "Cannone da 47/32"}
		{"zis3_chn" "ZiS-3"}
		{"type_97_150mm_chn" "150mm Situokesi mortar"}
		{"amr35-13mm_chn" "AMR35 ZT 1-13mm"}
		{"sgrw42_chn" "M1 mortar"}
		{"zpu-4" "ZPU-4"}
		{"t-26_td_custom" "AT-1"}
