		{"mp"		
			{"chn"
				{"ap_miner" "Combat Engineer (AP mines)"}
				{"at_miner" "Combat Engineer (AT mines)"}
				{"at_rifle" "AT infantry"}
				{"at_rifle2" "AT infantry"}
				{"elite" "Elite - smg"}
				{"elite2" "Elite - mgunner"}
				{"elite3" "Elite - rifle"}
				{"engineer" "Engineer"}
				{"flamer" "Flamethrower infantry"}
				{"home_guard" "National Defence"}
				{"home_guard2" "National Defence"}
				{"mgun" "Machine Gunner"}
				{"mgun2" "Machine gunner"}
				{"mgun3" "Machine gunner"}
				{"medic" "Medic"}
				{"oficer" "Officer"}
				{"rifle" "Rifleman"}
				{"rifle2" "Rifleman"}
				{"rifle3" "Rifleman"}
				{"saper" "Sapper"}
				{"smg" "SMG infantry"}
				{"smg2" "SMG infantry"}
				{"sniper" "Sniper"}
				{"sturmovik" "Stormtrooper - smg"}
				{"sturmovik2" "Stormtrooper - rifle"}
				{"sturmovik3" "Stormtrooper - mgunner"}
				{"sturmovik4" "Stormtrooper - AT rifle"}
				{"tankman" "Tank crew"}
				{"tankman2" "Tank crew"}
				{"tankman2_39" "Tank commander"}
				{"radioman" "Radio Operator"}
				{"squadleader" "Squad Leader"}
				{"vehicle_supporter" "Soldier"}
				{"vehicle_supporter_39" "Soldier"}
				{"vehicle_supporter_40" "Soldier"}
				{"vehicle_supporter_42" "Soldier"}
				{"vehicle_supporter_44" "Soldier"}
				{"smg_42" "SMG infantry"}
				{"smg2_42" "SMG infantry"}
				{"squadleader_42" "Squad Leader"}
				{"elite_42" "Elite - smg"}
				{"elite2_42" "Elite - mgunner"}
				{"elite3_42" "Elite - rifle"}
				{"sturmovik_42" "Stormtrooper - smg"}
				{"sturmovik2_42" "Stormtrooper - rifle"}
				{"sturmovik3_42" "Stormtrooper - mgunner"}
				{"pilot" "pilot"}
			}
		}
	