		{"mp"		
			{"fra"
				{"at_miner" "<c(c3baae)>combat engineer (vehicle)"}
				{"ap_miner" "<c(c3baae)>combat engineer (infantry)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>foreign legionnaire"}
				{"elite2" "<c(c3baae)>foreign legionnaire"}
				{"elite3" "<c(c3baae)>foreign legionnaire"}
                                {"elite_at" "<c(c3baae)>foreign legionnaire"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>resistance"}
				{"home_guard2" "<c(c3baae)>resistance"}
				{"home_guard3" "<c(c3baae)>resistance"}
				{"home_guard4" "<c(c3baae)>resistance"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"mgun2" "<c(c3baae)>polish volunteer"}
				{"oficer" "<c(c3baae)>officer"}
				{"oficer_arty" "<c(c3baae)>artillery officer"}			
                                {"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"rifle3" "<c(c3baae)>polish voulenteer"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"smg3" "<c(c3baae)>demolition specialist"}
				{"smg4" "<c(c3baae)>SMG infantry"}
                                {"sniper" "<c(c3baae)>sniper"}
				{"sturmovik" "<c(c3baae)>french sas"}
				{"sturmovik2" "<c(c3baae)>french sas"}
				{"sturmovik3" "<c(c3baae)>french sas"}
				{"sturmovik4" "<c(c3baae)>french sas"}
				{"sturmovik4b" "<c(c3baae)>french sas"}
				{"sturmovik5" "<c(c3baae)>french sas"}
				{"sturmovik5b" "<c(c3baae)>french sas"}
				{"sturmovik6" "<c(c3baae)>french sas"}
				{"sturmovik6b" "<c(c3baae)>french sas"}
				{"sturmovik7" "<c(c3baae)>french sas"}
                                {"sturmovik7b" "<c(c3baae)>french sas"}
                                {"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
		}