		{"mp"		
			{"fin"
				{"at_miner" "<c(c3baae)>combat engineer (vehicle)"}
				{"ap_miner" "<c(c3baae)>combat engineer (infantry)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>kaukopartio jaeger"}
                {"elite_at" "<c(c3baae)>kaukopartio jaeger"}
				{"elite_at2" "<c(c3baae)>toerni detatchment AT infantry"}
				{"elite_sniper" "<c(c3baae)>toerni detatchment sniper"}
				{"elite2" "<c(c3baae)>kaukopartio jaeger"}
                {"elite3" "<c(c3baae)>kaukopartio jaeger"}
				{"elite4" "<c(c3baae)>trench cleaner"}
                {"elite5" "<c(c3baae)>trench cleaner"}
				{"elite6" "<c(c3baae)>trench cleaner"}
                {"elite7" "<c(c3baae)>toerni detatchment jaeger"}
				{"elite8" "<c(c3baae)>toerni detatchment jaeger"}
                {"elite9" "<c(c3baae)>toerni detatchment machine gunner"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>reservist"}
				{"home_guard2" "<c(c3baae)>reservist"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"mgun2" "<c(c3baae)>polish volunteer"}
				{"mgun3" "<c(c3baae)>swedish volunteer"}
				{"oficer" "<c(c3baae)>officer"}		
                {"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"rifle3" "<c(c3baae)>swedish voulenteer"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"smg3" "<c(c3baae)>demolition specialist"}
				{"smg4" "<c(c3baae)>swedish voulenteer"}
				{"smg5" "<c(c3baae)>swedish voulenteer"}
                {"sniper" "<c(c3baae)>sniper"}
                {"sniper2" "<c(c3baae)>white death"}
				{"sturmovik" "<c(c3baae)>border jaeger"}
				{"sturmovik2" "<c(c3baae)>border jaeger"}
				{"sturmovik3" "<c(c3baae)>border jaeger"}
				{"sturmovik4" "<c(c3baae)>border jaeger"}
				{"sturmovik4b" "<c(c3baae)>border jaeger"}
				{"sturmovik5" "<c(c3baae)>border jaeger"}
				{"sturmovik5b" "<c(c3baae)>border jaeger"}
				{"sturmovik6" "<c(c3baae)>border jaeger"}
				{"sturmovik6b" "<c(c3baae)>border jaeger"}
				{"sturmovik7" "<c(c3baae)>border jaeger"}
                {"sturmovik7b" "<c(c3baae)>border jaeger"}
                {"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
		}