		{"universal_carrier_anz" "The Universal Carrier, also known as the Bren Gun Carrier from the light machine gun armament, is a common name describing a family of light armoured tracked vehicles built by Vickers-Armstrong and other companies.The Carrier, 3-inch Mortar was a design based on the 2 Pounder Carrier with a 3-inch mortar mounted in place of the 2 pounder. Designed to enable the mortar to have 360 degree traverse and to be fired either from the vehicle, or dismounted. 400 were produced and were ultimately sent as military aid to the Nationalist Chinese Army."}
		{"willysmb_anz" "Over a short period of time, three US companies -- Willys, Ford and Bantam -- worked together to develop a reliable and efficient off-roader to suit military needs. Production began in 1941, and it quickly proved its worth on the battlefield. Its excellent speed, and its capacity to mount large-calibre machine guns, made the Willys one of the finest army vehicles of WWII."}
		{"m30kangaroo" This vehicle is simply the chassis of the Preist without the howitzer. The 50.cal support means this unit acts like a slower, armored halftrack."}
		{"bedford_anz" "Truck that comes with infantry ammo, mortar ammo and TNT."}
		{"bedford_art_anz" "Truck that comes tank and artillery ammo."}
		{"bedford_eng_anz" "Truck that comes with Sandbags, Barricades and Barbed Wire."}
		{"r35_anz" "The Renault R35 a slow, but solid French tank that is primarily used for infantry support. The 37mm cannon is useful against tanks, but not recommended. Medium AT guns will kill this tank, so beware."}
		{"m1139_anz" "This Italian light tank is primarily used for infantry support, or a risky 20mm counter. It's duel machine guns are very useful for suppressing infantry, while the 37mm cannon can deal some decent damage versus tanks."}
		{"m1340_anz" "This an upgraded version of the Fiat M11/39. It retains the duel MG setup, but with increased armor and a 47mm cannon."}
		{"kangaroo" "The Ram Kangaroo is a fast, armored transport vehicle aimed to penetrate enemy lines and transport troops to any desired location. Feel free to transport AT men, flamethrowers or even soliders armed with MGs."}
		{"m3grant_anz" "The M3 Grant is an american made medium tank, primarily used for infantry support or as a 20mm killer. It has 2 cannons, a 75mm and a 37mm, while also boasting multiple machine guns for infantry supression. This tank however will certainly struggle against other medium tanks of its calibre."}
		{"ram" "The Ram tank is essentially a 6-pdr AT gun put onto an armored chassis. This is an excellent counter to any light tank, and can hold its own against medium tanks like the Panzer Ausf.H, while easily taking care of the Ausf.G and the Chi Nu."}
		
















