		{"203b4" "<c(c3baae)>super heavy self-propelled howitzer</c>"}
		{"achilles" "<c(c3baae)>heavy tank destroyer</c>"}
		{"archer" "<c(c3baae)>medium tank destroyer</c>"}
		{"bedford_6art" "<c(c3baae)>supply truck</c>"}
		{"bedford_eng" "<c(c3baae)>engineer truck</c>"}
		{"bedford_inf" "<c(c3baae)>supply truck</c>"}
		{"bishop" "<c(c3baae)>medium self-propelled howitzer</c>"}
		{"bl6" "<c(c3baae)>heavy field howitzer</c>"}
		{"blitz3_6art" "<c(c3baae)>supply truck</c>"}
		{"blitz3_6eng" "<c(c3baae)>engineer truck</c>"}
		{"blitz3_6inf" "<c(c3baae)>supply truck</c>"}
		{"bm13" "<c(c3baae)>rocket artillery</c>"}
		{"bm_8_24" "<c(c3baae)>rocket artillery</c>"}
		{"bm37" "<c(c3baae)></c>"}
		{"bofors" "<c(c3baae)>AA gun</c>"}
		{"browning_stan" "<c(c3baae)></c>"}
		{"brummbar" "<c(c3baae)>medium self-propelled gun</c>"}
		{"bs3" "<c(c3baae)>super heavy AT gun</c>"}
		{"chi-ha120" "<c(c3baae)>medium self-propelled gun</c>"}
		{"cromwell_mk_vi" "<c(c3baae)>medium self-propelled gun</c>"}
		{"crusaderaa2" "<c(c3baae)>AA tank</c>"}
		{"crusaderaa1" "<c(c3baae)>AA tank</c>"}
		{"churchill_avre" "<c(c3baae)>super heavy self-propelled gun</c>"}
		{"churchill_crocodile" "<c(c3baae)>flame tank</c>"}
		{"d1" "<c(c3baae)>heavy field howitzer</c>"}
		{"degtyarev_stan" "<c(c3baae)></c>"}
		{"elefant" "<c(c3baae)>heavy tank destroyer</c>"}
		{"flak37" "<c(c3baae)>AA gun</c>"}
		{"flak38_wheeled" "<c(c3baae)>AA gun</c>"}
		{"gmc_art" "<c(c3baae)>supply truck</c>"}
		{"gmc_eng" "<c(c3baae)>engineer truck</c>"}
		{"gmc_inf" "<c(c3baae)>supply truck</c>"}
		{"ha-to" "<c(c3baae)>heavy rocket artillery</c>"}
		{"hetzer" "<c(c3baae)>medium tank destroyer</c>"}
		{"ho-ni1" "<c(c3baae)>light tank destroyer</c>"}
		{"ho-ni2" "<c(c3baae)>medium self-propelled howitzer</c>"}
		{"ho-ni_3" "<c(c3baae)>light tank destroyer</c>"}
		{"ho-ri" "<c(c3baae)>heavy tank destroyer</c>"}
		{"ho-ri_1" "<c(c3baae)>heavy tank destroyer</c>"}
		{"ho-ro" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"hummel" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"isu122" "<c(c3baae)>medium self-propelled gun</c>"}
		{"isu152" "<c(c3baae)>heavy self-propelled gun</c>"}
		{"isuzutx40art" "<c(c3baae)>supply truck</c>"}
		{"isuzutx40_aa" "<c(c3baae)>AA vehicle</c>"}
		{"isuzutx40_eng" "<c(c3baae)>engineer truck</c>"}
		{"isuzutx40_inf" "<c(c3baae)>supply truck</c>"}
		{"jagdpanther" "<c(c3baae)>heavy tank destroyer</c>"}
		{"jagdpanzer_iv" "<c(c3baae)>medium tank destroyer</c>"}
		{"jagdtiger" "<c(c3baae)>heavy tank destroyer</c>"}
		{"k61" "<c(c3baae)>AA gun</c>"}
		{"kpvt" "<c(c3baae)>heavy MG</c>"}
		{"kv2" "<c(c3baae)>heavy self-propelled gun</c>"}
		{"land_mattress" "<c(c3baae)>rocket artillery</c>"}
		{"lefh18" "<c(c3baae)>medium field howitzer</c>"}
		{"m10wolverine" "<c(c3baae)>medium tank destroyer</c>"}
		{"m114" "<c(c3baae)>heavy field howitzer</c>"}
		{"m12gmc" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"m18" "<c(c3baae)>light tank destroyer</c>"}
		{"m19" "<c(c3baae)>AA tank</c>"}
		{"m1mortar" "<c(c3baae)></c>"}
		{"m1_57mm" "<c(c3baae)>medium AT gun</c>"}
		{"m2a1l" "<c(c3baae)>medium field howitzer</c>"}
		{"m30_1938" "<c(c3baae)>medium field howitzer</c>"}
		{"m37" "<c(c3baae)>light AT gun</c>"}
		{"m36" "<c(c3baae)>heavy tank destroyer</c>"}
		{"m3cannon" "<c(c3baae)>light AT gun</c>"}
		{"m4a3c" "<c(c3baae)>rocket artillery</c>"}
		{"m4a3m" "<c(c3baae)>minesweeper</c>"}
		{"m4a3m_eng" "<c(c3baae)>minesweeper</c>"}
		{"m4a3_105" "<c(c3baae)>medium self-propelled gun</c>"}
		{"m4a3_zippo" "<c(c3baae)>flame tank</c>"}
		{"m4a4_tulip" "<c(c3baae)>rocket artillery</c>"}
		{"m5" "<c(c3baae)>heavy AT gun</c>"}
		{"m7" "<c(c3baae)>medium self-propelled howitzer</c>"}
		{"m72" "<c(c3baae)>motorcycle</c>"}
		{"m7_eng" "<c(c3baae)>medium self-propelled howitzer</c>"}
		{"m8_howitzer" "<c(c3baae)>light howitzer</c>"}
		{"marder_3h" "<c(c3baae)>light tank destroyer</c>"}
		{"maxson" "<c(c3baae)>AA gun</c>"}
		{"mg42_stan" "<c(c3baae)></c>"}
		{"ml3" "<c(c3baae)></c>"}
		{"nashorn" "<c(c3baae)>medium tank destroyer</c>"}
		{"nebelwerfer41" "<c(c3baae)>rocket artillery</c>"}
		{"nebelwerfer42" "<c(c3baae)>rocket artillery</c>"}
		{"oerlikon" "<c(c3baae)>AA gun</c>"}
		{"pak38" "<c(c3baae)>medium AT gun</c>"}
		{"pak40" "<c(c3baae)>heavy AT gun</c>"}
		{"pak41-le" "<c(c3baae)>light AT gun</c>"}
		{"pak43" "<c(c3baae)>super heavy AT gun</c>"}
		{"pak47" "<c(c3baae)>light AT gun</c>"}
		{"pak57" "<c(c3baae)>medium AT gun</c>"}
		{"pdr25" "<c(c3baae)>medium field howitzer</c>"}
		{"pz1" "<c(c3baae)>AA tank</c>"}
		{"pz1b" "<c(c3baae)>tankette</c>"}
		{"pz3m" "<c(c3baae)>minesweeper</c>"}
		{"qf2" "<c(c3baae)>light AT gun</c>"}
		{"qf6" "<c(c3baae)>medium AT gun</c>"}
		{"qf17" "<c(c3baae)>heavy AT gun</c>"}
		{"r12" "<c(c3baae)>motorcycle</c>"}
		{"sdkfz303" "<c(c3baae)>remote-controlled bomb</c>"}
		{"sdkfz4" "<c(c3baae)>rocket artillery</c>"}
		{"sfh18" "<c(c3baae)>heavy field howitzer</c>"}
		{"sgrw42" "<c(c3baae)></c>"}
		{"ss-d" "<c(c3baae)>flame minesweeper</c>"}
		{"stug4g" "<c(c3baae)>medium tank destroyer</c>"}
		{"sturmtiger" "<c(c3baae)>heavy rocket artillery</c>"}
		{"stuh42" "<c(c3baae)>medium self-propelled gun</c>"}
		{"su100" "<c(c3baae)>heavy tank destroyer</c>"}
		{"su122" "<c(c3baae)>medium self-propelled gun</c>"}
		{"su76" "<c(c3baae)>light tank destroyer</c>"}
		{"su85" "<c(c3baae)>medium tank destroyer</c>"}
		{"t26" "<c(c3baae)>tankette</c>"}
		{"t34m" "<c(c3baae)>minesweeper</c>"}
		{"t90_75m" "<c(c3baae)>heavy AT gun</c>"}
		{"t91_105m" "<c(c3baae)>medium field howitzer</c>"}
		{"type1hmg_stan" "<c(c3baae)></c>"}
		{"type2_20mm" "<c(c3baae)>AA gun</c>"}
		{"type4_200mm" "<c(c3baae)>rocket artillery</c>"}
		{"type4_75mm" "<c(c3baae)>AA gun</c>"}
		{"type94" "<c(c3baae)></c>"}
		{"type96_150mm" "<c(c3baae)>heavy field howitzer</c>"}
		{"type_97_150mm" "<c(c3baae)>heavy mortar</c>"}
		{"vickers" "<c(c3baae)>AA gun</c>"}
		{"vickers_stan" "<c(c3baae)></c>"}
		{"welberwind" "<c(c3baae)>AA tank</c>"}
		{"wespe" "<c(c3baae)>medium self-propelled howitzer</c>"}
		{"zis2" "<c(c3baae)>heavy AT gun</c>"}
		{"zis3" "<c(c3baae)>medium AT gun</c>"}
		{"zis5art" "<c(c3baae)>supply truck</c>"}
		{"zis5inf" "<c(c3baae)>supply truck</c>"}
		{"zis5_eng" "<c(c3baae)>engineer truck</c>"}
		{"zis_30" "<c(c3baae)>light tank destroyer</c>"}
		{"zsu37" "<c(c3baae)>AA tank</c>"}
		;------ NP
		{"np_bm31" "<c(c3baae)>Rocket launcher</c>"}
		{"np_bs3" "<c(c3baae)>Heavy anti-tank gun</c>"}
		{"np_52k" "<c(c3baae)>Anti-aircraft gun</c>"}
		{"np_voroshilovets" "<c(c3baae)>Heavy Tractor</c>"}
		{"np_f22" "<c(c3baae)>Divisional gun</c>"}
		{"np_pak36r" "<c(c3baae)>Anti-tank gun</c>"}
		{"np_marder135" "<c(c3baae)>Light tank destroyer</c>"}
		{"np_sdkfz135_1" "<c(c3baae)>Self-propelled howitzer</c>"}
		{"np_bm13n" "<c(c3baae)>Rocket launcher</c>"}
		{"np_zis42" "<c(c3baae)>Halftrack</c>"}
		{"np_zis42_61k" "<c(c3baae)>Self-propelled AA gun</c>"}
		{"np_pak44" "<c(c3baae)>Heavy anti-tank gun</c>"}
		{"np_sdkfz8" "<c(c3baae)>Halftrack Truck</c>"}
		{"np_ml20" "<c(c3baae)>Howitzer-gun</c>"}
		{"np_sdkfz250_1" "<c(c3baae)>Light Armoured Halftrack</c>"}
		{"np_sdkfz250_10" "<c(c3baae)>Light Armoured Halftrack</c>"}
		{"np_sdkfz250_11" "<c(c3baae)>Light Armoured Halftrack</c>"}
		{"np_sdkfz250_7" "<c(c3baae)>Self-propelled mortar</c>"}
		{"np_sdkfz250_7_1" "<c(c3baae)>Ammunition Transporter</c>"}
		{"np_sdKfz251_1w" "<c(c3baae)>Multiple rocket launcher</c>"}
		{"np_m5" "<c(c3baae)>Armoured Halftrack</c>"}
		{"np_m2" "<c(c3baae)>Armoured Halftrack</c>"}
		{"np_m2_tr" "<c(c3baae)>Armoured Halftrack</c>"}
		{"np_t48" "<c(c3baae)>Self-propelled tank destroyer</c>"}
		{"np_t48_us" "<c(c3baae)>Self-propelled tank destroyer</c>"}
		{"np_t48_eng" "<c(c3baae)>Self-propelled tank destroyer</c>"}
		{"np_t19" "<c(c3baae)>Self-propelled howitzer</c>"} 
		{"np_m17" "<c(c3baae)>Armoured Halftrack</c>"}
		{"np_m15a1" "<c(c3baae)>Self-propelled AA gun</c>"}
		{"np_zis5_en" "<c(c3baae)>Engineer truck</c>"}
		{"np_zis5_fuel" "<c(c3baae)>Fuel truck</c>"}
		{"np_voroshilovets_52k" "<c(c3baae)>Self-propelled AA gun</c>"}
		{"np_su14" "<c(c3baae)>Self-propelled heavy howitzer</c>"}
		{"np_29k" "<c(c3baae)>Self-propelled AA gun</c>"}
		{"su85m" "<c(c3baae)>medium tank destroyer</c>"}
		{"np_mercedesl3000_art" "<c(c3baae)>supply truck</c>"}
		{"np_opel_eng" "<c(c3baae)>engineer truck</c>"}
		{"np_opel_inf" "<c(c3baae)>supply truck</c>"}
		{"np_zis5_art" "<c(c3baae)>supply truck</c>"}
		{"np_zis5_inf" "<c(c3baae)>supply truck</c>"}
		{"np_bm13" "<c(c3baae)>rocket artillery</c>"}
		{"np_sdkfz4" "<c(c3baae)>rocket artillery</c>"}
		{"dickermax" "<c(c3baae)>heavy tank destroyer</c>"}
		{"stug3c" "<c(c3baae)>medium self-propelled gun</c>"}
		{"stug3f" "<c(c3baae)>medium tank destroyer</c>"}
		{"stug3g" "<c(c3baae)>medium tank destroyer</c>"}
		{"t34m2" "<c(c3baae)>minesweeper</c>"}
		{"ot34_2" "<c(c3baae)>flame tank</c>"}
		{"ot-130" "<c(c3baae)>flame tank</c>"}
		{"pz3_m_flamer" "<c(c3baae)>flame tank</c>"}
		{"np_pak40" "<c(c3baae)>medium AT gun</c>"}
		{"np_opel_halftrack" "<c(c3baae)>halftrack</c>"}
		{"np_52k_43" "<c(c3baae)>Anti-aircraft gun</c>"}
		{"np_opel_art" "<c(c3baae)>supply truck</c>"}
		{"np_d1" "<c(c3baae)>Howitzer-gun</c>"}
		{"zrinyi2" "<c(c3baae)>medium self-propelled gun</c>"}
		{"zrinyi1" "<c(c3baae)>tank destroyer (prototype)</c>"}
		{"nimrod" "<c(c3baae)>AA tank</c>"}
		{"tas_44td" "<c(c3baae)>tank destroyer (prototype)</c>"}
		{"tas_44m" "<c(c3baae)>medium tank (prototype)</c>"}
		{"m4hst" "<c(c3baae)>high speed tractor</c>"}
		{"155mm_longtom" "<c(c3baae)>field gun</c>"}
		{"schwarzlose_hun" "<c(c3baae)></c>"}
		{"solothurn_hun" "<c(c3baae)>heavy AT rifle</c>"}
		{"40mm_40m" "<c(c3baae)>light AT gun</c>"}
		{"np_pak40_hun" "<c(c3baae)>medium AT gun</c>"}
		{"pak38_hun" "<c(c3baae)>medium AT gun</c>"}
		{"m36b1" "<c(c3baae)>heavy tank destroyer</c>"}
		{"schwimmwagen" "<c(c3baae)>amphibia</c>"}
		{"te-ke" "<c(c3baae)>tankette</c>"}
		{"panzerjager" "<c(c3baae)>light tank destroyer</c>"}
		{"kettenkard" "<c(c3baae)>light tractor</c>"}
		{"np_sdkfz8_flak" "<c(c3baae)>self-propelled AA gun</c>"}
		{"np_su12" "<c(c3baae)>self-propelled gun</c>"}
		{"ferdinand" "<c(c3baae)>heavy tank destroyer</c>"}
		{"na-to" "<c(c3baae)>medium tank destroyer</c>"}
		{"ta-se" "<c(c3baae)>self-propelled AA gun</c>"}
		{"bl45" "<c(c3baae)>medium field gun</c>"}
		{"obice210_hun" "<c(c3baae)>heavy field howitzer</c>"}
		{"qf13" "<c(c3baae)>light field gun</c>"}
		{"stz3" "<c(c3baae)>medium tractor</c>"}
		{"stz3_chn" "<c(c3baae)>medium tractor</c>"}
		{"gun_carrier_3_inch" "<c(c3baae)>Self-propelled mortar</c>"}
		{"m4halftrack" "<c(c3baae)>Self-propelled mortar</c>"}
		{"gun_carrier_chn" "<c(c3baae)>Self-propelled mortar</c>"}
		{"fw190f8" "<c(c3baae)>Fighter aircraft</c>"}
		{"fw190f8_hun" "<c(c3baae)>Fighter aircraft</c>"}
		{"i-16" "<c(c3baae)>Fighter aircraft</c>"}
		{"i-16_ru" "<c(c3baae)>Fighter aircraft</c>"}
		{"mk3mustang" "<c(c3baae)>Fighter aircraft</c>"}
		{"a6m5" "<c(c3baae)>Fighter aircraft</c>"}
		{"la5fn" "<c(c3baae)>Fighter aircraft</c>"}
		{"bf109" "<c(c3baae)>Fighter aircraft</c>"}
		{"p51mustang" "<c(c3baae)>Fighter aircraft</c>"}
		{"bf109g_fin" "<c(c3baae)>Fighter aircraft</c>"}
		{"mc_205" "<c(c3baae)>Fighter aircraft</c>"}
		{"bf109g_rom" "<c(c3baae)>Fighter aircraft</c>"}
		{"spitfiremk1a" "<c(c3baae)>Fighter aircraft</c>"}
		{"spitfiremk1a_fra" "<c(c3baae)>Fighter aircraft</c>"}
		{"bm8-48" "<c(c3baae)>rocket artillery</c>"}
		{"pm38" "<c(c3baae)></c>"}
		{"granatwerfer42" "<c(c3baae)></c>"}
		{"somua_mcg" "<c(c3baae)>tractor</c>"}
		{"morser18" "<c(c3baae)>heavy howitzer</c>"}